"""Bedtime mobility (owner request 2026-10-05): gentle mobility exercises for the evening,
in the exercise library tagged `kind: "mobility"`, and mobility programmes — by the kind
of day (easy run, hard session, long run, ride, swim, a sitting day) and by body region.
The evening report picks one by the day's activities (metrics/mobility.py).

What the evidence supports and what it doesn't: regular stretching increases range of
motion (Behm et al., 2016; for the calf and ankle Radford et al., 2006; for the back of
the shoulder McClure et al., 2007), but it doesn't prevent running injuries (Lauersen
et al., 2014) or muscle soreness after training (Herbert et al., 2011). Rolling with a
ball or a foam roller lowers perceived soreness a little (Wiewelhove et al., 2019).
Slow breathing around 6 breaths a minute raises vagally mediated HRV during and after
the session (Laborde et al., 2022), and 4 months of stretching improved sleep in
people with chronic insomnia as much as resistance exercise (D'Aurea et al., 2019). So
the evening mobility is offered for relaxation, range of motion and the way into sleep,
never as injury prevention. Holds are gentle (a mild pull, never pain); the choice of
exercises for each kind of day follows the posture and the tissues the day loads and is
the product team's working assumption. Texts are our own.
"""

# Exercises: same shape as programs_library.EXERCISES, plus `kind` and `min` (minutes
# the exercise takes with both sides, for the session length).
MOBILITY_EXERCISES = {
    "mob_calf_wall": {"name": "Protažení lýtka u zdi", "area": "lýtko", "kind": "mobility", "min": 2,
                      "how": "Opřete se rukama o zeď, zadní noha propnutá s patou na zemi, přední pokrčená. Boky jemně posuňte ke zdi.",
                      "dose": "2 × 30 s každá noha", "perWeek": 7,
                      "steps": ["Postavte se čelem ke zdi a opřete se o ni dlaněmi ve výšce ramen.",
                                "Jednu nohu dejte dozadu, koleno propnuté, pata celá na zemi a špička míří dopředu.",
                                "Přední koleno pokrčte a boky pomalu posuňte ke zdi, až ucítíte mírný tah v lýtku zadní nohy.",
                                "Vydržte a klidně dýchejte, pak vyměňte nohy."],
                      "mistakes": ["Pata zadní nohy se zvedá ze země.", "Houpání místo klidné výdrže."]},
    "mob_soleus_wall": {"name": "Protažení hlubokého lýtka u zdi", "area": "lýtko a Achillova šlacha", "kind": "mobility", "min": 2,
                        "how": "Stejně jako u lýtka u zdi, jen zadní koleno pokrčte, až ucítíte tah níž, nad patou.",
                        "dose": "2 × 30 s každá noha", "perWeek": 7,
                        "steps": ["Opřete se o zeď a nohy dejte do mírného výkroku, zadní chodidlo kratší krok za předním.",
                                  "Obě kolena pokrčte a váhu přeneste na zadní nohu, pata zůstává na zemi.",
                                  "Tah ucítíte níž v lýtku, nad patou. Vydržte a dýchejte.",
                                  "Vyměňte nohy."],
                        "mistakes": ["Zvednutá pata.", "Tah do bolesti v Achillově šlaše."],
                        "caution": "Při bolesti úponu Achillovy šlachy na patě protahujte jen do velmi mírného tahu, nebo cvik vynechte."},
    "mob_knee_wall": {"name": "Koleno ke zdi (hybnost kotníku)", "area": "kotník", "kind": "mobility", "min": 2,
                      "how": "V mírném výkroku čelem ke zdi tlačte přední koleno ke zdi, pata zůstává na zemi. Plynule tam a zpět.",
                      "dose": "10 opakování každá noha", "perWeek": 7,
                      "steps": ["Postavte se čelem ke zdi, přední chodidlo asi na šířku dlaně od ní.",
                                "Pokrčte přední koleno a tlačte ho nad druhý prst směrem ke zdi, pata se nezvedá.",
                                "Vraťte se zpět a pohyb plynule opakujte.",
                                "Když se koleno zdi dotkne snadno, posuňte chodidlo o kousek dál."],
                      "mistakes": ["Koleno padá dovnitř.", "Pata se odlepuje od země."]},
    "mob_foot_ball": {"name": "Masáž chodidla míčkem", "area": "chodidlo", "kind": "mobility", "min": 2,
                      "how": "Vsedě nebo ve stoji pomalu válejte chodidlo po tenisovém míčku od paty k prstům. Tlak jen příjemný.",
                      "dose": "1 min každá noha", "perWeek": 7,
                      "steps": ["Posaďte se a pod chodidlo dejte tenisový nebo masážní míček.",
                                "Pomalu válejte chodidlo od paty k prstům a zpět, s mírným tlakem.",
                                "Na citlivých místech chvíli zůstaňte a dýchejte.",
                                "Vyměňte nohy."],
                      "mistakes": ["Tlak do ostré bolesti.", "Rychlé přejíždění bez zastavení."]},
    "mob_toes": {"name": "Protažení prstů v kleku", "area": "chodidlo a prsty", "kind": "mobility", "min": 1,
                 "how": "Klekněte si s prsty nohou opřenými o zem a pomalu se posaďte k patám, až ucítíte tah v chodidle.",
                 "dose": "3 × 20 s", "perWeek": 7,
                 "steps": ["Klekněte si a prsty nohou opřete o podložku, paty míří nahoru.",
                           "Pomalu se posaďte směrem k patám, ruce si můžete opřít před tělo.",
                           "Jděte jen do mírného tahu v chodidle a pod prsty a vydržte.",
                           "Povolte, krátce si odpočiňte a opakujte."],
                 "mistakes": ["Prudké dosednutí celou vahou.", "Výdrž přes bolest v palci."]},
    "mob_hamstring_strap": {"name": "Protažení zadní strany stehna vleže s ručníkem", "area": "zadní strana stehna", "kind": "mobility", "min": 2,
                            "how": "Vleže na zádech zvedněte propnutou nohu s ručníkem kolem chodidla, až ucítíte mírný tah. Druhá noha leží.",
                            "dose": "2 × 30 s každá noha", "perWeek": 7,
                            "steps": ["Lehněte si na záda a kolem chodidla jedné nohy dejte ručník nebo pásek.",
                                      "Nohu s mírně povoleným kolenem zvedněte nahoru, druhá noha leží natažená na zemi.",
                                      "Ručníkem nohu přitáhněte jen do mírného tahu v zadní straně stehna a vydržte.",
                                      "Pomalu položte a vyměňte nohy."],
                            "mistakes": ["Zvedání pánve nebo druhé nohy ze země.", "Tahání do bolesti pod kolenem."]},
    "mob_hip_flexor": {"name": "Protažení přední strany kyčle v kleku", "area": "přední strana kyčle", "kind": "mobility", "min": 2,
                       "how": "V kleku na jednom koleni podsaďte pánev a jemně ji posuňte dopředu, až ucítíte tah vpředu v kyčli zadní nohy.",
                       "dose": "2 × 30 s každá strana", "perWeek": 7,
                       "steps": ["Klekněte si na jedno koleno, pod něj dejte polštář, druhá noha je vpředu s chodidlem na zemi.",
                                 "Podsaďte pánev, jako byste chtěli zastrčit ocas, a zpevněte hýždi zadní nohy.",
                                 "Pomalu posuňte pánev dopředu, až ucítíte tah vpředu v kyčli zadní nohy.",
                                 "Vydržte, dýchejte a vyměňte strany."],
                       "mistakes": ["Prohnutí v bedrech místo podsazení pánve.", "Přední koleno daleko před špičkou."]},
    "mob_quad_side": {"name": "Protažení přední strany stehna vleže na boku", "area": "přední strana stehna", "kind": "mobility", "min": 2,
                      "how": "Vleže na boku chyťte horní nohu za kotník a přitáhněte patu k hýždi. Kolena u sebe, pánev mírně podsazená.",
                      "dose": "2 × 30 s každá noha", "perWeek": 7,
                      "steps": ["Lehněte si na bok, hlavu opřete o spodní ruku.",
                                "Horní nohu pokrčte a chyťte ji rukou za kotník nebo za nohavici.",
                                "Přitáhněte patu k hýždi, kolena držte u sebe a pánev mírně podsaďte.",
                                "Vydržte v mírném tahu a vyměňte strany."],
                      "mistakes": ["Prohnutí v bedrech.", "Koleno horní nohy odjíždí dopředu."]},
    "mob_figure4": {"name": "Protažení hýždě vleže (čtyřka)", "area": "hýždě", "kind": "mobility", "min": 2,
                    "how": "Vleže na zádech položte kotník jedné nohy na koleno druhé a přitáhněte si spodní stehno k hrudníku.",
                    "dose": "2 × 30 s každá strana", "perWeek": 7,
                    "steps": ["Lehněte si na záda, kolena pokrčte a chodidla dejte na zem.",
                              "Kotník pravé nohy položte na levé koleno, jako číslo 4.",
                              "Chyťte levé stehno a pomalu ho přitáhněte k hrudníku, až ucítíte tah v pravé hýždi.",
                              "Vydržte, hlava a ramena zůstávají na zemi. Vyměňte strany."],
                    "mistakes": ["Zvedání hlavy a ramen.", "Tlačení do bolesti v koleni."]},
    "mob_9090": {"name": "Kyčle 90/90", "area": "kyčle (rotace)", "kind": "mobility", "min": 2,
                 "how": "Vsedě s oběma koleny pokrčenými do pravého úhlu pomalu překlápějte kolena z jedné strany na druhou.",
                 "dose": "8 opakování na každou stranu", "perWeek": 7,
                 "steps": ["Posaďte se na zem, chodidla dejte na šířku větší než ramena a kolena pokrčte.",
                           "Opřete se rukama za tělem a obě kolena pomalu sklopte na jednu stranu.",
                           "Přední a zadní noha mají v kolenou zhruba pravý úhel.",
                           "Plynule překlopte kolena na druhou stranu a pokračujte."],
                 "mistakes": ["Švih místo pomalého pohybu.", "Tlačení do bolesti v kyčli nebo koleni."]},
    "mob_butterfly": {"name": "Motýlek vsedě", "area": "vnitřní strana stehen", "kind": "mobility", "min": 1,
                      "how": "Vsedě spojte chodidla, kolena nechte padat do stran a s rovnými zády se mírně předkloňte.",
                      "dose": "2 × 30 s", "perWeek": 7,
                      "steps": ["Posaďte se, spojte chodidla a přitáhněte je k sobě tak blízko, jak je to příjemné.",
                                "Kolena nechte volně klesnout do stran.",
                                "S rovnými zády se mírně předkloňte z kyčlí, až ucítíte tah ve vnitřní straně stehen.",
                                "Vydržte a dýchejte."],
                      "mistakes": ["Tlačení koleny dolů rukama silou.", "Kulatá záda."]},
    "mob_it_cross": {"name": "Protažení vnější strany kyčle vleže", "area": "vnější strana kyčle a stehna", "kind": "mobility", "min": 2,
                     "how": "Vleže na zádech přetáhněte propnutou nohu přes tělo k zemi na opačné straně. Ramena zůstávají na zemi.",
                     "dose": "2 × 30 s každá noha", "perWeek": 7,
                     "steps": ["Lehněte si na záda a paže dejte do stran.",
                               "Pravou nohu zvedněte a přetáhněte ji přes tělo doleva, levou rukou ji můžete přidržet.",
                               "Ramena zůstávají na zemi, tah ucítíte ve vnější straně pravé kyčle a stehna.",
                               "Vydržte a vyměňte strany."],
                     "mistakes": ["Zvedání ramen ze země.", "Prudké stáčení do bolesti v kříži."]},
    "mob_lumbar_rot": {"name": "Překlápění kolen vleže", "area": "bederní páteř", "kind": "mobility", "min": 1,
                       "how": "Vleže na zádech s pokrčenými koleny je pomalu sklápějte z jedné strany na druhou, ramena zůstávají na zemi.",
                       "dose": "10 opakování na každou stranu", "perWeek": 7,
                       "steps": ["Lehněte si na záda, kolena pokrčte, chodidla u sebe na zemi a paže dejte do stran.",
                                 "Pomalu sklopte obě kolena na jednu stranu, jen tak daleko, jak je to příjemné.",
                                 "Vraťte je doprostřed a sklopte na druhou stranu.",
                                 "Dýchejte plynule s pohybem."],
                       "mistakes": ["Zvedání ramen.", "Rychlé házení koleny ze strany na stranu."]},
    "mob_knees_chest": {"name": "Kolena k hrudníku", "area": "bederní páteř", "kind": "mobility", "min": 1,
                        "how": "Vleže na zádech přitáhněte obě kolena k hrudníku a jemně se pohupujte ze strany na stranu.",
                        "dose": "2 × 30 s", "perWeek": 7,
                        "steps": ["Lehněte si na záda a obě kolena přitáhněte rukama k hrudníku.",
                                  "Hlava a ramena zůstávají uvolněně na zemi.",
                                  "Jemně se pohupujte ze strany na stranu, jako byste masírovali kříž o podložku.",
                                  "Dýchejte do břicha."],
                        "mistakes": ["Zvedání hlavy.", "Tahání kolen silou do bolesti."]},
    "mob_child": {"name": "Dětská pozice", "area": "záda a ramena", "kind": "mobility", "min": 1,
                  "how": "Ze sedu na patách se předkloňte a natáhněte paže před sebe na zem. Čelo opřete a dýchejte do zad.",
                  "dose": "2 × 30 s", "perWeek": 7,
                  "steps": ["Klekněte si, kolena dejte od sebe na šířku boků a palce nohou k sobě.",
                            "Posaďte se k patám a předkloňte se, paže natáhněte daleko před sebe.",
                            "Čelo opřete o podložku a uvolněte ramena.",
                            "Dýchejte pomalu a nechte dech roztahovat záda."],
                  "mistakes": ["Napjatá ramena u uší.", "Tlačení do bolesti v kolenou, podložte je polštářem."]},
    "mob_child_side": {"name": "Dětská pozice s úklonem", "area": "široký zádový sval a bok", "kind": "mobility", "min": 2,
                       "how": "V dětské pozici přesuňte obě ruce na jednu stranu, až ucítíte tah v boku a pod lopatkou na straně opačné.",
                       "dose": "2 × 30 s každá strana", "perWeek": 7,
                       "steps": ["Zaujměte dětskou pozici s pažemi nataženými před sebou.",
                                 "Obě ruce přesuňte po zemi doprava.",
                                 "Tah ucítíte v levém boku a pod levou lopatkou. Vydržte a dýchejte do boku.",
                                 "Vraťte ruce doprostřed a vyměňte strany."],
                       "mistakes": ["Zvedání pánve z pat.", "Napjatá ramena."]},
    "mob_cat_cow": {"name": "Kočka a kráva", "area": "páteř", "kind": "mobility", "min": 1,
                    "how": "Na všech čtyřech střídavě vyhrbte záda ke stropu a pomalu je prohněte, s dechem.",
                    "dose": "10 pomalých opakování", "perWeek": 7,
                    "steps": ["Klekněte si na všechny čtyři, dlaně pod rameny a kolena pod kyčlemi.",
                              "S výdechem vyhrbte záda ke stropu a hlavu sklopte.",
                              "S nádechem záda pomalu prohněte a pohled zvedněte mírně dopředu.",
                              "Pohyb jde obratel po obratli, plynule a bez bolesti."],
                    "mistakes": ["Rychlé tempo.", "Pohyb jen v krku a v bedrech, hrudník zůstává ztuhlý."]},
    "mob_open_book": {"name": "Otevírání knihy vleže na boku", "area": "hrudní páteř", "kind": "mobility", "min": 2,
                      "how": "Vleže na boku s pokrčenými koleny otevřete horní paži obloukem na druhou stranu a pohledem ji sledujte.",
                      "dose": "8 opakování každá strana", "perWeek": 7,
                      "steps": ["Lehněte si na bok, kolena pokrčte do pravého úhlu a paže natáhněte před sebe dlaněmi k sobě.",
                                "Horní paži zvedněte a obloukem ji otevřete na druhou stranu, hlava se otáčí s ní.",
                                "Kolena zůstávají u sebe na zemi, otáčí se hrudník.",
                                "Pomalu paži vraťte zpět. Po sérii vyměňte stranu."],
                      "mistakes": ["Kolena se zvedají a pánev se otáčí s hrudníkem.", "Švih paží místo pomalého pohybu."]},
    "mob_thread_needle": {"name": "Provlékání jehly", "area": "hrudní páteř a ramena", "kind": "mobility", "min": 2,
                          "how": "Na všech čtyřech provlékněte jednu ruku pod tělem na druhou stranu a opřete se ramenem o zem.",
                          "dose": "6 opakování každá strana", "perWeek": 7,
                          "steps": ["Klekněte si na všechny čtyři.",
                                    "Pravou ruku provlékněte pod tělem doleva, až se pravé rameno a spánek opřou o zem.",
                                    "Chvíli vydržte a dýchejte do horní části zad.",
                                    "Ruku vytáhněte zpět a otevřete ji ke stropu. Po sérii vyměňte strany."],
                          "mistakes": ["Pánev ujíždí do strany.", "Tlak do ramene, které bolí."]},
    "mob_doorway_chest": {"name": "Protažení hrudníku ve dveřích", "area": "prsní svaly a přední strana ramen", "kind": "mobility", "min": 1,
                          "how": "Předloktí opřete o zárubeň s loktem v úrovni ramene a pomalu vykročte dopředu.",
                          "dose": "2 × 30 s každá strana", "perWeek": 7,
                          "steps": ["Postavte se do dveří a předloktí opřete o zárubeň, loket ve výšce ramene.",
                                    "Vykročte jednou nohou dopředu a hrudník pomalu posuňte skrz dveře.",
                                    "Tah ucítíte v hrudníku a na přední straně ramene. Vydržte.",
                                    "Vyměňte strany."],
                          "mistakes": ["Loket nad úrovní ramene.", "Brnění v ruce, pak loket snižte."]},
    "mob_cross_body": {"name": "Přitažení paže přes hrudník", "area": "zadní strana ramene", "kind": "mobility", "min": 1,
                       "how": "Nataženou paži přitáhněte druhou rukou přes hrudník, rameno držte dole.",
                       "dose": "2 × 30 s každá strana", "perWeek": 7,
                       "steps": ["Zvedněte jednu paži před sebe do výšky ramen.",
                                 "Druhou rukou ji chyťte nad loktem a přitáhněte ji přes hrudník.",
                                 "Rameno držte dole, tah ucítíte vzadu na rameni. Vydržte.",
                                 "Vyměňte strany."],
                       "mistakes": ["Zvednuté rameno k uchu.", "Otáčení trupu za paží."]},
    "mob_neck_side": {"name": "Úklon hlavy", "area": "krk a šíje", "kind": "mobility", "min": 1,
                      "how": "Vsedě uklonte hlavu k rameni a opačné rameno nechte klesnout dolů. Jemně, bez tlaku rukou.",
                      "dose": "2 × 20 s každá strana", "perWeek": 7,
                      "steps": ["Posaďte se zpříma a uvolněte ramena.",
                                "Ukloňte hlavu uchem k pravému rameni, pohled zůstává dopředu.",
                                "Levé rameno nechte klesnout dolů, až ucítíte tah na levé straně krku.",
                                "Vydržte a vyměňte strany."],
                      "mistakes": ["Tahání hlavy rukou.", "Zvedání ramene k uchu."]},
    "mob_chin_tuck": {"name": "Zasunutí brady", "area": "krk", "kind": "mobility", "min": 1,
                      "how": "Vsedě nebo vleže zasuňte bradu rovně dozadu, jako byste dělali dvojitou bradu, a krátce vydržte.",
                      "dose": "10 opakování po 3 s", "perWeek": 7,
                      "steps": ["Posaďte se zpříma nebo si lehněte na záda.",
                                "Bradu zasuňte rovně dozadu, hlava se nesklání ani nezaklání.",
                                "Vydržte 3 sekundy a povolte.",
                                "Opakujte pomalu."],
                      "mistakes": ["Kývání hlavou dolů.", "Zatínání čelistí."]},
    "mob_legs_wall": {"name": "Nohy na zdi", "area": "uvolnění nohou", "kind": "mobility", "min": 3,
                      "how": "Vleže na zádech opřete natažené nohy o zeď, hýždě co nejblíž ke zdi. Ležte a klidně dýchejte.",
                      "dose": "3 min", "perWeek": 7,
                      "steps": ["Posaďte se bokem ke zdi a při lehnutí na záda zvedněte nohy na zeď.",
                                "Hýždě posuňte tak blízko ke zdi, jak je to příjemné, kolena mohou být mírně pokrčená.",
                                "Paže položte volně podél těla a zavřete oči.",
                                "Ležte a klidně dýchejte."],
                      "mistakes": ["Napjatá zadní strana stehen, kolena povolte.", "Mravenčení v nohou, pak nohy spusťte."]},
    "mob_breathing": {"name": "Pomalé dýchání vleže", "area": "dech a zklidnění", "kind": "mobility", "min": 5,
                      "how": "Vleže na zádech dýchejte nosem do břicha: nádech 4 sekundy, výdech 6 sekund, zhruba 6 dechů za minutu.",
                      "dose": "5 min", "perWeek": 7,
                      "steps": ["Lehněte si na záda, kolena pokrčte nebo nohy opřete o postel. Jednu ruku dejte na břicho.",
                                "Nadechujte se nosem 4 sekundy, břicho se zvedá pod rukou.",
                                "Vydechujte pomalu 6 sekund, nosem nebo sešpulenými rty.",
                                "Pokračujte 5 minut. Když se dech zadrhne, chvíli dýchejte volně."],
                      "mistakes": ["Nádech do hrudníku a ramen.", "Tlačení dechu silou."]},
}

PHYSIO_STRETCH = "https://www.physio-pedia.com/Stretching"
_BASE_EVIDENCE = ("Pravidelné protahování zvětšuje rozsah pohybu (Behm et al., 2016), zraněním při běhu ani svalové bolesti po "
                  "tréninku ale nepředchází (Lauersen et al., 2014; Herbert et al., 2011). Večerní mobilita je proto pro uvolnění, "
                  "pohyblivost a lepší usínání: pomalé dýchání kolem 6 dechů za minutu zvyšuje variabilitu tepu (Laborde et al., 2022) "
                  "a čtyři měsíce protahování zlepšily spánek lidí s nespavostí stejně jako posilování (D'Aurea et al., 2019).")
_BASE_REFS = ["Behm et al., 2016", "Lauersen et al., 2014", "Herbert et al., 2011", "Laborde et al., 2022", "D'Aurea et al., 2019"]
_ASSUMPTION = "Výběr cviků pro tento typ dne a dávkování jsou pracovní předpoklad. Protahujte jen do mírného tahu, nikdy do bolesti."


def _prog(key, name, sub, summary, exercises, extra_ev="", extra_refs=(), assumption=_ASSUMPTION, day=None):
    return {"key": key, "group": "mobility", "sub": sub, "day": day, "physio": PHYSIO_STRETCH, "name": name,
            "weeks": None, "perWeek": 7, "when": "před spaním", "match": [], "summary": summary,
            "exercises": exercises, "minutes": sum(MOBILITY_EXERCISES[x]["min"] for x in exercises),
            "evidence": (extra_ev + " " if extra_ev else "") + _BASE_EVIDENCE,
            "refs": list(extra_refs) + _BASE_REFS, "assumption": assumption}


CALF_EV = "Protahování lýtka mírně zvětšuje rozsah pohybu v kotníku (Radford et al., 2006)."
BALL_EV = "Válení míčkem nebo válcem mírně snižuje pocit svalové bolesti (Wiewelhove et al., 2019)."
SHOULDER_EV = ("Přitahování paže přes hrudník zlepšilo za 4 týdny vnitřní rotaci ramene u lidí se ztuhlou zadní stranou "
               "ramene víc než bez cvičení (McClure et al., 2007).")

MOBILITY_PROGRAMS = [
    # by the kind of day
    _prog("mob_run", "Mobilita po lehkém běhu", "day",
          "Lýtka, přední strana kyčle, zadní strana stehna a hýždě, na závěr pomalý dech.",
          ["mob_calf_wall", "mob_soleus_wall", "mob_hip_flexor", "mob_hamstring_strap", "mob_figure4", "mob_breathing"],
          CALF_EV, ["Radford et al., 2006"], day="lehký"),
    _prog("mob_quality", "Mobilita po tvrdém tréninku", "day",
          "Po intervalech hlavně zklidnění: jemně stehna a kyčle, záda a delší pomalý dech. Zadní strana stehna jen lehce.",
          ["mob_quad_side", "mob_hip_flexor", "mob_calf_wall", "mob_lumbar_rot", "mob_child", "mob_breathing"],
          day="kvalitní"),
    _prog("mob_long", "Mobilita po dlouhém běhu", "day",
          "Chodidla a lýtka po mnoha krocích, kyčle a kříž, nohy nahoru a pomalý dech.",
          ["mob_foot_ball", "mob_soleus_wall", "mob_calf_wall", "mob_9090", "mob_figure4", "mob_lumbar_rot", "mob_legs_wall",
           "mob_breathing"],
          f"{CALF_EV} {BALL_EV}", ["Radford et al., 2006", "Wiewelhove et al., 2019"], day="dlouhý"),
    _prog("mob_bike", "Mobilita po kole", "day",
          "Po hodinách v předklonu: přední strana kyčle a stehna, hrudní páteř, hrudník a krk.",
          ["mob_hip_flexor", "mob_quad_side", "mob_open_book", "mob_doorway_chest", "mob_neck_side", "mob_figure4", "mob_breathing"],
          day="kolo"),
    _prog("mob_swim", "Mobilita po plavání", "day",
          "Ramena, široký zádový sval, hrudník a hrudní páteř, krk.",
          ["mob_cross_body", "mob_child_side", "mob_doorway_chest", "mob_thread_needle", "mob_neck_side", "mob_breathing"],
          SHOULDER_EV, ["McClure et al., 2007"], day="plavání"),
    _prog("mob_sedentary", "Mobilita po sedavém nebo klidném dni", "day",
          "Pro běžce po dni bez tréninku a hodně sezení: kyčle, páteř, kotníky a krk, ať se zítra běží volněji.",
          ["mob_hip_flexor", "mob_cat_cow", "mob_open_book", "mob_9090", "mob_knee_wall", "mob_chin_tuck", "mob_figure4",
           "mob_breathing"],
          CALF_EV, ["Radford et al., 2006"], day="sedavý"),
    # by body region
    _prog("mob_r_feet", "Mobilita: chodidla, kotníky a lýtka", "region",
          "Chodidlo, prsty, hybnost kotníku a obě části lýtka.",
          ["mob_foot_ball", "mob_toes", "mob_knee_wall", "mob_calf_wall", "mob_soleus_wall"],
          f"{CALF_EV} {BALL_EV}", ["Radford et al., 2006", "Wiewelhove et al., 2019"]),
    _prog("mob_r_hips", "Mobilita: kyčle a hýždě", "region",
          "Přední strana kyčle, rotace kyčlí, hýždě, vnější a vnitřní strana.",
          ["mob_hip_flexor", "mob_9090", "mob_figure4", "mob_it_cross", "mob_butterfly"]),
    _prog("mob_r_thighs", "Mobilita: stehna", "region",
          "Přední, zadní, vnitřní a vnější strana stehna.",
          ["mob_quad_side", "mob_hamstring_strap", "mob_butterfly", "mob_it_cross"]),
    _prog("mob_r_back", "Mobilita: záda a páteř", "region",
          "Celá páteř od kříže po hrudník.",
          ["mob_cat_cow", "mob_child", "mob_open_book", "mob_lumbar_rot", "mob_knees_chest"]),
    _prog("mob_r_shoulders", "Mobilita: ramena, hrudník a krk", "region",
          "Přední a zadní strana ramen, hrudník, horní část zad a krk.",
          ["mob_doorway_chest", "mob_cross_body", "mob_thread_needle", "mob_neck_side", "mob_chin_tuck"],
          SHOULDER_EV, ["McClure et al., 2007"]),
    _prog("mob_full", "Mobilita: celé tělo", "region",
          "Krátce všechno podstatné od páteře po lýtka, na závěr pomalý dech.",
          ["mob_cat_cow", "mob_hip_flexor", "mob_hamstring_strap", "mob_figure4", "mob_open_book", "mob_calf_wall",
           "mob_breathing"]),
]

MOBILITY_REFERENCES = {
    "Behm et al., 2016": "Behm, D. G., Blazevich, A. J., Kay, A. D., & McHugh, M. (2016). Acute effects of muscle stretching on physical performance, range of motion, and injury incidence in healthy active individuals: A systematic review. Applied Physiology, Nutrition, and Metabolism, 41(1), 1–11.",
    "Herbert et al., 2011": "Herbert, R. D., de Noronha, M., & Kamper, S. J. (2011). Stretching to prevent or reduce muscle soreness after exercise. Cochrane Database of Systematic Reviews, (7), CD004577.",
    "Laborde et al., 2022": "Laborde, S., Allen, M. S., Borges, U., Dosseville, F., Hosang, T. J., Iskra, M., Mosley, E., Salvotti, C., Spolverato, L., Zammit, N., & Javelle, F. (2022). Effects of voluntary slow breathing on heart rate and heart rate variability: A systematic review and a meta-analysis. Neuroscience & Biobehavioral Reviews, 138, 104711.",
    "D'Aurea et al., 2019": "D'Aurea, C. V. R., Poyares, D., Passos, G. S., Santana, M. G., Youngstedt, S. D., Souza, A. A., Bicudo, J., Tufik, S., & de Mello, M. T. (2019). Effects of resistance exercise training and stretching on chronic insomnia. Brazilian Journal of Psychiatry, 41(1), 51–57.",
    "Radford et al., 2006": "Radford, J. A., Burns, J., Buchbinder, R., Landorf, K. B., & Cook, C. (2006). Does stretching increase ankle dorsiflexion range of motion? A systematic review. British Journal of Sports Medicine, 40(10), 870–875.",
    "Wiewelhove et al., 2019": "Wiewelhove, T., Döweling, A., Schneider, C., Hottenrott, L., Meyer, T., Kellmann, M., Pfeiffer, M., & Ferrauti, A. (2019). A meta-analysis of the effects of foam rolling on performance and recovery. Frontiers in Physiology, 10, 376.",
    "McClure et al., 2007": "McClure, P., Balaicuis, J., Heiland, D., Broersma, M. E., Thorndike, C. K., & Wood, A. (2007). A randomized controlled comparison of stretching procedures for posterior shoulder tightness. Journal of Orthopaedic & Sports Physical Therapy, 37(3), 108–114.",
}
