"""Feedback railway#116 — ready-made exercise programs for the most common running
problems, which the runner can start on their own, and the exercise library a runner
builds their own session from.

No free exercise database fits a commercial physio product as it is: free-exercise-db
(Unlicense) covers gym exercises and its images have no known licence, wger data are
Creative Commons per entry and mostly gym exercises, Physiopedia is non-commercial. So
the exercises and the programs are written here, from published protocols, each with its
source. Doses that no source fixes are the product team's working assumptions and are
marked as such (`assumption`). The programs are for self-management of mild complaints,
not a replacement for an examination; they wait for review by a Došlap physiotherapist
(`reviewed` = False until then).

Pain rule for every program: pain up to 5/10 during an exercise is acceptable, it must
settle by the next morning and must not grow from week to week (Silbernagel et al.,
2007); bone pain follows the complete absence of pain instead (Warden et al., 2014).
"""

PAIN_RULE = ("Bolest při cvičení do 5 z 10 je v pořádku, do druhého rána musí odeznít a nesmí týden od týdne růst. "
             "Když roste nebo je ráno horší, uberte počet opakování.")

# id → exercise. `how` = execution in two or three short sentences, `dose` = default dose,
# `steps` = numbered execution for the exercise detail, `mistakes` = the common faults to
# watch, `caution` = when to leave the exercise out. All texts are written for Došlap from
# the cited protocols and general exercise technique; no text or image is taken over from
# Physiopedia (CC BY-NC-SA, non-commercial), which the detail only links to.
EXERCISES = {
    "heel_raise_2": {"name": "Výpony na obou nohách", "area": "lýtko a Achillova šlacha",
                     "how": "Stoupněte si na špičky plynule nahoru a pomalu dolů, kolena propnutá. Držte se lehce zdi.",
                     "dose": "3 × 15", "perWeek": 7,
                     "steps": ["Postavte se na šířku pánve, prsty dopředu, a jednou rukou se lehce opřete o zeď.",
                               "Za 2 sekundy se zvedněte co nejvýš na špičky, váha jde přes palec a druhý prst.",
                               "Nahoře krátce vydržte a za 3 sekundy se spusťte zpět na paty.",
                               "Kolena zůstávají propnutá a tělo se nenaklání dopředu."],
                     "mistakes": ["Rychlé houpání nahoru a dolů bez kontroly.", "Vytáčení kotníků ven, kdy váha přejde na malíček."]},
    "heel_raise_1": {"name": "Výpony na jedné noze", "area": "lýtko a Achillova šlacha",
                     "how": "Na jedné noze nahoru za 2 s, nahoře krátká výdrž, dolů za 3 s. Postupně přidejte batoh se zátěží.",
                     "dose": "3 × 15", "perWeek": 7,
                     "steps": ["Stoupněte si na jednu nohu, druhou pokrčte a prsty ruky se lehce dotkněte zdi.",
                               "Za 2 sekundy se zvedněte na špičku a nahoře vydržte 1 sekundu.",
                               "Za 3 sekundy se spusťte až na patu.",
                               "Když zvládnete 3 × 15 bez potíží, přidejte batoh se zátěží."],
                     "mistakes": ["Opírání o zeď celou vahou.", "Neúplný rozsah, kdy pata nejde naplno nahoru ani dolů."]},
    "ecc_straight": {"name": "Spouštění paty ze schodu, propnuté koleno", "area": "Achillova šlacha",
                     "how": "Na hraně schodu se zvedněte na obou nohách, pak se pomalu spouštějte jen na bolavé noze pod úroveň schodu. Nahoru zase oběma.",
                     "dose": "3 × 15, 2× denně", "perWeek": 14,
                     "steps": ["Stoupněte si přední částí chodidel na hranu schodu tak, aby paty přesahovaly.",
                               "Zvedněte se na obou nohách na špičky.",
                               "Přeneste váhu na bolavou nohu a za 3 sekundy spusťte patu pod úroveň schodu, koleno zůstává propnuté.",
                               "Zpět nahoru se vraťte oběma nohama nebo s pomocí zdravé nohy."],
                     "mistakes": ["Zvedání nahoru jen bolavou nohou, cvik pracuje hlavně při spouštění.", "Rychlé spadnutí dolů bez brzdění."]},
    "ecc_bent": {"name": "Spouštění paty ze schodu, pokrčené koleno", "area": "Achillova šlacha a soleus",
                 "how": "Stejně jako se spouštěním paty, jen s mírně pokrčeným kolenem, aby pracoval hlubší lýtkový sval.",
                 "dose": "3 × 15, 2× denně", "perWeek": 14,
                 "steps": ["Postavte se na hranu schodu stejně jako u spouštění s propnutým kolenem.",
                           "Zvedněte se na obou nohách na špičky a mírně pokrčte kolena.",
                           "S pokrčeným kolenem se na bolavé noze za 3 sekundy spusťte pod úroveň schodu.",
                           "Nahoru se vraťte oběma nohama."],
                 "mistakes": ["Propínání kolena během spouštění.", "Přenášení váhy do zdi místo do chodidla."]},
    "seated_calf": {"name": "Výpony vsedě se zátěží", "area": "soleus (hluboké lýtko)",
                    "how": "Vsedě s koleny v pravém úhlu a se zátěží na stehnech zvedejte paty. Pomalu nahoru i dolů.",
                    "dose": "3 × 12", "perWeek": 3,
                    "steps": ["Sedněte si na židli s koleny v pravém úhlu a chodidly na zemi.",
                              "Na stehna těsně nad koleny položte zátěž, třeba batoh nebo činku.",
                              "Zvedněte paty co nejvýš a nahoře vydržte 1 sekundu.",
                              "Pomalu je spusťte zpět na zem."],
                    "mistakes": ["Příliš lehká zátěž, poslední opakování mají být náročná.", "Tlačení rukama do stehen místo práce lýtek."]},
    "hops": {"name": "Poskoky na místě", "area": "lýtko a šlacha, pružnost",
             "how": "Lehké rytmické poskoky na obou nohách, později na jedné. Jen když při výponech nic nebolí.",
             "dose": "3 × 20 s", "perWeek": 3,
             "steps": ["Postavte se na šířku pánve s volnými pažemi.",
                       "Poskakujte lehce a rytmicky z přední části chodidel, paty se země skoro nedotýkají.",
                       "Kolena jsou jen mírně pokrčená a odraz jde hlavně z kotníků.",
                       "Když to jde bez bolesti, zkuste poskoky na jedné noze."],
             "mistakes": ["Hlučné dopady s propadnutím do kolen.", "Začátek poskoků ve chvíli, kdy ještě bolí výpony."],
             "caution": "Zařaďte je až ve chvíli, kdy výpony na jedné noze nebolí."},
    "towel_raise": {"name": "Výpon na jedné noze s ručníkem pod prsty", "area": "plantární fascie",
                    "how": "Srolovaný ručník pod prsty, aby byly zvednuté. Nahoru 3 s, nahoře 2 s výdrž, dolů 3 s. Zátěž přidejte batohem.",
                    "dose": "3 × 12 (max. zátěž na 12 opakování)", "perWeek": 3,
                    "steps": ["Srolujte ručník, položte ho na zem a opřete o něj prsty jedné nohy, aby byly zvednuté.",
                              "Stoupněte si na tuto nohu, druhou pokrčte a rukou se lehce opřete.",
                              "Za 3 sekundy se zvedněte, nahoře vydržte 2 sekundy a za 3 sekundy se spusťte.",
                              "Zátěž volte tak, abyste zvládli právě 12 opakování, a přidávejte ji batohem."],
                    "mistakes": ["Prsty sklouznou z ručníku.", "Příliš rychlé tempo nahoru i dolů."]},
    "side_abd": {"name": "Unožování vleže na boku", "area": "hýžďové svaly (abduktory kyčle)",
                 "how": "Vleže na boku zvedněte horní propnutou nohu mírně za tělo, špička dopředu. Pomalu dolů.",
                 "dose": "3 × 15", "perWeek": 4,
                 "steps": ["Lehněte si na bok, spodní nohu můžete pokrčit, horní je propnutá v linii s tělem.",
                           "Horní nohu zvedněte mírně za osu těla, špička míří dopředu, ne ke stropu.",
                           "Jděte jen do výšky, kterou zvládnete bez překlopení pánve, a nahoře vydržte 1 sekundu.",
                           "Pomalu nohu spusťte."],
                 "mistakes": ["Noha jde před tělo a práci přebírá přední strana stehna.", "Pánev se překlápí dozadu."]},
    "clamshell": {"name": "Mušle", "area": "hýžďové svaly",
                  "how": "Vleže na boku s pokrčenými koleny a spojenými chodidly otvírejte horní koleno, pánev se neotáčí. Zesílíte gumou.",
                  "dose": "3 × 15", "perWeek": 4,
                  "steps": ["Lehněte si na bok, kyčle a kolena pokrčte a chodidla dejte k sobě.",
                            "Horní koleno otevřete nahoru, chodidla zůstávají spojená.",
                            "Pánev se nepřetáčí dozadu, pro kontrolu na ni položte ruku.",
                            "Pomalu zavřete. Ztížíte si to gumou kolem stehen nad koleny."],
                  "mistakes": ["Přetáčení pánve dozadu, aby koleno šlo výš.", "Rychlé švihání kolenem."]},
    "bridge": {"name": "Most", "area": "hýždě a zadní strana stehen",
               "how": "Vleže na zádech s pokrčenými koleny zvedněte pánev do přímky, nahoře 2 s výdrž. Pokročile na jedné noze.",
               "dose": "3 × 12", "perWeek": 4,
               "steps": ["Lehněte si na záda, kolena pokrčte, chodidla dejte na šířku pánve a ruce podél těla.",
                         "Zatlačte patami do země a zvedněte pánev, až jsou kolena, kyčle a ramena v jedné linii.",
                         "Nahoře vydržte 2 sekundy se zpevněnými hýžděmi.",
                         "Pomalu spusťte pánev na zem. Pokročilejší verze je na jedné noze."],
               "mistakes": ["Prohýbání v bedrech místo zvednutí silou hýždí.", "Kolena padají od sebe nebo k sobě."]},
    "wall_squat": {"name": "Dřep u zdi", "area": "kvadriceps",
                   "how": "Zády u zdi sjeďte do hloubky, která nebolí, a vydržte. Kolena míří nad špičky.",
                   "dose": "5 × 30 s", "perWeek": 4,
                   "steps": ["Opřete se zády o zeď, chodidla dejte kousek před sebe na šířku pánve.",
                             "Sjeďte po zdi do hloubky, která nebolí, nejvýš do pravého úhlu v kolenou.",
                             "Kolena míří nad druhý prst a váha je na celých chodidlech.",
                             "Vydržte a pak se po zdi vysuňte zpět nahoru."],
                   "mistakes": ["Kolena padají dovnitř.", "Zadržování dechu během výdrže."]},
    "step_up": {"name": "Výstup na schod", "area": "kvadriceps a hýždě",
                "how": "Vystupte na schod jednou nohou a pomalu sestupte zpět. Koleno nepadá dovnitř, pánev zůstává rovně.",
                "dose": "3 × 10 každá noha", "perWeek": 3,
                "steps": ["Postavte se před schod nebo stabilní bednu a jednu nohu na něj položte celým chodidlem.",
                          "Přeneste váhu na horní nohu a vystupte nahoru, spodní noha jen přisune.",
                          "Pomalu sestupte zpět a pohyb brzděte horní nohou.",
                          "Koleno míří nad špičku a pánev zůstává vodorovně."],
                "mistakes": ["Odraz spodní nohou, který práci ubere.", "Koleno padá dovnitř."]},
    "knee_ext": {"name": "Předkopávání vsedě", "area": "kvadriceps",
                 "how": "Vsedě propněte koleno proti odporu gumy nebo zátěže na kotníku a pomalu povolte.",
                 "dose": "3 × 12", "perWeek": 3,
                 "steps": ["Sedněte si na židli a kolem kotníku dejte zátěž nebo gumu uchycenou za nohu židle.",
                           "Za 2 sekundy propněte koleno do natažení.",
                           "Nahoře vydržte 1 sekundu a za 3 sekundy povolte."],
                 "mistakes": ["Švihání nohou.", "Zaklánění trupu, které pomáhá zvednout zátěž."]},
    "pelvic_drop": {"name": "Spouštění pánve na schodu", "area": "střední hýžďový sval",
                    "how": "Stůjte bokem na schodu na jedné noze, druhou nechte volně viset. Spusťte pánev na volné straně dolů a zvedněte ji zpět silou stojné kyčle.",
                    "dose": "3 × 15", "perWeek": 4,
                    "steps": ["Stoupněte si bokem na schod na jednu nohu, druhá visí volně přes okraj.",
                              "Stojná noha zůstává propnutá a ramena v klidu.",
                              "Spusťte pánev na straně volné nohy o pár centimetrů dolů.",
                              "Silou stojné kyčle ji zvedněte zpět nad vodorovnou úroveň."],
                    "mistakes": ["Pokrčování stojného kolena.", "Naklánění trupu do strany."]},
    "sl_squat": {"name": "Dřep na jedné noze", "area": "kyčel a koleno, kontrola",
                 "how": "Pomalý mělký dřep na jedné noze před zrcadlem, koleno nad špičkou, pánev rovně.",
                 "dose": "3 × 8", "perWeek": 3,
                 "steps": ["Stoupněte si na jednu nohu, nejlépe před zrcadlo, ruce dejte před tělo.",
                           "Pomalu se spouštějte do mělkého dřepu, jako byste si chtěli sednout.",
                           "Koleno míří nad druhý prst a pánev zůstává rovně.",
                           "Vraťte se nahoru. Hloubku přidávejte, jen když udržíte kontrolu."],
                 "mistakes": ["Koleno padá dovnitř.", "Pánev klesá na straně volné nohy."]},
    "toe_raise": {"name": "Zvedání špiček", "area": "přední sval holeně",
                  "how": "Zády u zdi s patami kousek od ní zvedejte špičky co nejvýš a pomalu dolů.",
                  "dose": "3 × 20", "perWeek": 4,
                  "steps": ["Opřete se zády o zeď, paty dejte asi na délku chodidla od ní.",
                            "Zvedněte špičky co nejvýš k holením, paty zůstávají na zemi.",
                            "Pomalu je spusťte zpět."],
                  "mistakes": ["Rychlé plácání špičkami o zem.", "Odlepování zad od zdi."]},
    "balance": {"name": "Stoj na jedné noze", "area": "kotník a stabilita",
                "how": "Stoj na jedné noze s mírně pokrčeným kolenem. Ztížíte zavřenýma očima nebo na polštáři.",
                "dose": "3 × 30 s", "perWeek": 5,
                "steps": ["Postavte se na jednu nohu s mírně pokrčeným kolenem.",
                          "Pánev držte rovně a dívejte se před sebe.",
                          "Když 30 sekund zvládnete snadno, zavřete oči nebo se postavte na polštář."],
                "mistakes": ["Zamčené propnuté koleno.", "Opírání volné nohy o stojnou."]},
    "nordic": {"name": "Nordický hamstring", "area": "zadní strana stehen",
               "how": "Vkleče s fixovanými kotníky se pomalu naklánějte dopředu s rovnými zády, brzděte zadní stranou stehen, pak se zachyťte rukama.",
               "dose": "2–3 × 5–8", "perWeek": 2,
               "steps": ["Klekněte si na měkkou podložku, kotníky vám přidrží partner nebo je zapřete pod těžký nábytek.",
                         "Tělo držte rovně od kolen po hlavu a ruce dejte před hrudník.",
                         "Pomalu se naklánějte dopředu a pohyb brzděte zadní stranou stehen co nejdéle.",
                         "Když už pád neudržíte, zachyťte se rukama a odtlačte se zpět nahoru."],
               "mistakes": ["Předklon v kyčlích místo rovného těla.", "Rychlý pád bez brzdění."],
               "caution": "Zařaďte ho až ve chvíli, kdy zadní strana stehna při běžné chůzi a mostu nebolí."},
    "sl_rdl": {"name": "Rumunský mrtvý tah na jedné noze", "area": "hamstring a hýždě",
               "how": "Na jedné noze s mírně pokrčeným kolenem se předkloňte s rovnými zády, druhá noha jde dozadu. Zpět silou hýždě.",
               "dose": "3 × 8 každá noha", "perWeek": 2,
               "steps": ["Stoupněte si na jednu nohu s mírně pokrčeným kolenem.",
                         "Předkloňte se v kyčlích s rovnými zády, volná noha jde dozadu v linii s trupem.",
                         "Jděte tak hluboko, až ucítíte natažení zadní strany stehna.",
                         "Zpět se narovnejte silou hýždě stojné nohy."],
               "mistakes": ["Kulatá záda.", "Pánev se otáčí ke straně volné nohy."]},
    "bridge_iso": {"name": "Výdrž v mostu na patách", "area": "hamstring, šetrný začátek",
                   "how": "Most s patami dál od těla, pánev nahoru a výdrž. Na začátek při bolesti zadní strany stehna.",
                   "dose": "5 × 30 s", "perWeek": 5,
                   "steps": ["Lehněte si na záda a paty položte dál od těla než u běžného mostu, špičky mohou jít nahoru.",
                             "Zvedněte pánev, až je tělo v přímce.",
                             "Vydržte a plynule dýchejte, pak pomalu dolů."],
                   "mistakes": ["Prohnutá bedra.", "Výdrž přes ostrou bolest v zadní straně stehna."]},
    # Core for runners (railway: new programs). Exercise choice follows Physiopedia's
    # core stability overview only as a list of common exercises; the wording is our own.
    "plank": {"name": "Plank na předloktích", "area": "střed těla",
              "how": "Opora na předloktích a špičkách, tělo v jedné přímce od hlavy po paty. Dýchejte a vydržte.",
              "dose": "3 × 20–40 s", "perWeek": 3,
              "steps": ["Opřete se o předloktí, lokty dejte pod ramena.",
                        "Natáhněte nohy dozadu a opřete se o špičky, začít můžete i na kolenou.",
                        "Tělo držte v jedné přímce od hlavy po paty, lehce zpevněte břicho a hýždě.",
                        "Dýchejte plynule a vydržte."],
              "mistakes": ["Propadlá bedra.", "Pánev vystrčená příliš vysoko."]},
    "curl_up": {"name": "Zvednutí hlavy a ramen s výdrží (curl-up)", "area": "přímý břišní sval",
                "how": "Vleže na zádech s jednou pokrčenou nohou zvedněte hlavu a ramena jen kousek nad podložku a vydržte 10 s. Bedra zůstávají v klidu.",
                "dose": "3 × 5 výdrží po 10 s", "perWeek": 4,
                "steps": ["Lehněte si na záda, jednu nohu pokrčte a druhou nechte nataženou, ruce dejte pod bedra.",
                          "Zpevněte břicho a zvedněte hlavu a ramena jen pár centimetrů nad podložku.",
                          "Vydržte 10 sekund a plynule dýchejte.",
                          "Pomalu položte, po pěti výdržích vyměňte nohy."],
                "mistakes": ["Velký sed-leh místo malého zvednutí.", "Tahání hlavy rukama za krk."]},
    "pelvic_tilt": {"name": "Podsazení pánve a zvednutí pánve vleže", "area": "dolní část břicha",
                    "how": "Vleže s pokrčenými koleny podsaďte pánev, bedra přitiskněte k podložce, vydržte a povolte. Později přitáhněte kolena k hrudníku a pánev nadzvedněte.",
                    "dose": "3 × 10", "perWeek": 4,
                    "steps": ["Lehněte si na záda, kolena pokrčte a chodidla dejte na zem.",
                              "Podsaďte pánev, až se bedra dotknou podložky, a vydržte 5 sekund.",
                              "Povolte a opakujte.",
                              "Když to nebolí, zvedněte nohy a pánev pomalu nadzvedněte pár centimetrů nad podložku."],
                    "mistakes": ["Švih nohama místo práce břicha.", "Pokračování přes ostrou bolest v podbřišku."],
                    "caution": "Zvedání pánve zařaďte až ve chvíli, kdy podsazení pánve nebolí."},
    "add_squeeze": {"name": "Stlačování míče koleny", "area": "adduktory (tříslo)",
                    "how": "Vleže na zádech s pokrčenými koleny stlačte míč mezi koleny a vydržte 30 s. Síla jen do nepohodlí, ne do ostré bolesti.",
                    "dose": "10 × 30 s", "perWeek": 3,
                    "steps": ["Lehněte si na záda, kolena pokrčte a mezi ně dejte míč nebo srolovaný polštář.",
                              "Kolena stlačte proti míči a vydržte 30 sekund.",
                              "Povolte, krátce si odpočiňte a opakujte.",
                              "Sílu přidávejte postupně, bolest při cvičení nesmí přesáhnout 5 z 10."],
                    "mistakes": ["Zadržování dechu během výdrže.", "Stlačování do ostré bolesti v třísle."]},
    "side_adduction": {"name": "Přitahování spodní nohy vleže na boku", "area": "adduktory (tříslo)",
                       "how": "Vleže na boku opřete horní nohu chodidlem před tělem a spodní propnutou nohu zvedejte k horní. Pomalu dolů.",
                       "dose": "3 × 10 každá noha", "perWeek": 3,
                       "steps": ["Lehněte si na bok, hlavu opřete o spodní ruku.",
                                 "Horní nohu pokrčte a chodidlo položte na zem před spodní koleno.",
                                 "Spodní propnutou nohu zvedněte co nejvýš a nahoře vydržte 1 sekundu.",
                                 "Za 3 sekundy ji pomalu spusťte."],
                       "mistakes": ["Přetáčení pánve dozadu.", "Švihání nohou místo pomalého pohybu."]},
    "copenhagen": {"name": "Kodaňský plank (Copenhagen)", "area": "adduktory (tříslo)",
                   "how": "Boční plank s horní nohou na lavici: spodní nohu přitáhněte k lavici a pomalu ji spusťte. Začněte s kolenem na lavici.",
                   "dose": "2–3 × 5 každá strana", "perWeek": 2,
                   "steps": ["Lehněte si na bok vedle lavice, loket dejte pod rameno.",
                             "Horní nohu položte na lavici, na začátek kolenem, později kotníkem.",
                             "Zvedněte pánev do přímky a spodní nohu přitáhněte k lavici.",
                             "Pomalu ji spusťte k zemi a pánev položte."],
                   "mistakes": ["Pánev klesá k zemi.", "Začátek s kotníkem na lavici dřív, než to jde bez bolesti s kolenem."],
                   "caution": "Zařaďte ho až ve chvíli, kdy stlačování míče a přitahování nohy nebolí."},
    "side_plank": {"name": "Boční plank", "area": "střed těla",
                   "how": "Na boku s oporou o loket zvedněte pánev do přímky a vydržte. Lehčí verze je s pokrčenými koleny.",
                   "dose": "3 × 20 s každá strana", "perWeek": 3,
                   "steps": ["Lehněte si na bok, loket dejte pod rameno a nohy natáhněte na sebe.",
                             "Zvedněte pánev, až je tělo v přímce od hlavy po chodidla.",
                             "Vydržte a pak vyměňte stranu.",
                             "Lehčí verze je s pokrčenými koleny."],
                   "mistakes": ["Pánev klesá k zemi.", "Tělo se přetáčí dopředu nebo dozadu."]},
    "dead_bug": {"name": "Mrtvý brouk", "area": "střed těla",
                 "how": "Vleže na zádech pomalu natahujte opačnou ruku a nohu k zemi, bedra zůstávají na podložce.",
                 "dose": "3 × 8 každá strana", "perWeek": 3,
                 "steps": ["Lehněte si na záda, ruce natáhněte ke stropu, kyčle a kolena pokrčte do pravého úhlu.",
                           "Bedra přitiskněte k podložce.",
                           "Pomalu natáhněte jednu nohu a opačnou ruku k zemi, bedra se přitom nezvedají.",
                           "Vraťte se zpět a vystřídejte strany."],
                 "mistakes": ["Prohnutí beder při natažení nohy.", "Rychlé tempo bez kontroly."]},
    "bird_dog": {"name": "Bird dog (diagonála v kleku)", "area": "střed těla",
                 "how": "Na všech čtyřech natáhněte opačnou ruku a nohu do vodorovné polohy, záda zůstávají rovná.",
                 "dose": "3 × 8 každá strana", "perWeek": 3,
                 "steps": ["Klekněte si na všechny čtyři, dlaně pod rameny a kolena pod kyčlemi.",
                           "Záda držte rovně jako desku stolu.",
                           "Natáhněte jednu nohu dozadu a opačnou ruku dopředu do vodorovné polohy.",
                           "Vydržte 2 sekundy, vraťte se a vystřídejte strany."],
                 "mistakes": ["Zvedání nohy nad úroveň zad s prohnutím v bedrech.", "Přetáčení pánve do strany."]},
    # Runner's must-have (owner request 2026-10-03): the exercises of sessions A and B of
    # the 6-month durability programme (app/durability.py). Wording is our own.
    "pogo_hops": {"name": "Pogo poskoky", "area": "lýtko a Achillova šlacha, pružnost",
                  "how": "Rychlé nízké poskoky snožmo z kotníků, kolena skoro propnutá, co nejkratší kontakt se zemí.",
                  "dose": "3 × 20 s", "perWeek": 1,
                  "steps": ["Stoupněte si na šířku boků, ruce volně podél těla.",
                            "Odrážejte se jen z kotníků, kolena zůstávají skoro propnutá.",
                            "Dopadejte na přední část chodidla a hned se odrazte znovu, jako míček.",
                            "Držte rytmus a výšku po celou dobu série."],
                  "mistakes": ["Dopad na paty.", "Hluboké pokrčení kolen místo práce kotníků.", "Pokračování, když se kontakt prodlužuje."],
                  "caution": "Vynechte při bolesti Achillovy šlachy nad 3 z 10 nebo při bolesti kosti v holeni či chodidle."},
    "monster_walk": {"name": "Monster walk s gumou", "area": "hýžďové svaly (abduktory kyčle)",
                     "how": "S minibandem nad koleny nebo kotníky v podřepu kráčejte šikmo dopředu a pak dozadu, kolena tlačte ven.",
                     "dose": "2 × 12 kroků každým směrem", "perWeek": 1,
                     "steps": ["Natáhněte si minibandu nad kolena, pokročilí nad kotníky.",
                               "Postavte se do mírného podřepu, chodidla na šířku boků.",
                               "Kráčejte šikmo dopředu, střídavě vlevo a vpravo, guma je stále napnutá.",
                               "Stejným počtem kroků se vraťte šikmo dozadu."],
                     "mistakes": ["Kolena padají dovnitř.", "Kývání trupem ze strany na stranu.", "Povolená guma mezi kroky."]},
    "bulgarian_ss": {"name": "Bulharský dřep", "area": "kvadriceps a hýždě",
                     "how": "Zadní noha na lavici, přední daleko vpředu. Klesněte svisle dolů, až je přední stehno vodorovně, a silou přední nohy nahoru.",
                     "dose": "3 × 8 každá noha", "perWeek": 1,
                     "steps": ["Postavte se zády k lavici a nárt zadní nohy na ni položte.",
                               "Přední nohu dejte tak daleko, aby koleno v dřepu bylo nad chodidlem.",
                               "Klesněte svisle dolů, trup lehce nakloněný dopředu, s činkami v rukou.",
                               "Odtlačte se celým chodidlem přední nohy zpět nahoru."],
                     "mistakes": ["Přední koleno padá dovnitř.", "Odraz ze zadní nohy.", "Příliš krátký krok, pata se zvedá."]},
    "rdl": {"name": "Rumunský mrtvý tah", "area": "hamstring a hýždě",
            "how": "S činkou v rukou a mírně pokrčenými koleny se předkloňte v kyčlích s rovnými zády, činka jede po stehnech. Zpět silou hýždí.",
            "dose": "3 × 8", "perWeek": 1,
            "steps": ["Stoupněte si na šířku boků, činku nebo jednoručky držte před stehny.",
                      "Kolena lehce pokrčte a v této poloze je držte celou dobu.",
                      "Tlačte pánev dozadu a předklánějte se s rovnými zády, činka jede těsně po nohou.",
                      "Jakmile ucítíte natažení zadní strany stehen, vraťte se silou hýždí nahoru."],
            "mistakes": ["Kulatá záda.", "Činka daleko od těla.", "Dřep místo předklonu v kyčlích."]},
    "copenhagen_hold": {"name": "Kodaňský plank, výdrž", "area": "adduktory (tříslo)",
                        "how": "Boční plank s horní nohou na lavici a výdrž v přímce. Začněte s kolenem na lavici, později kotník.",
                        "dose": "2 × 20 s každá strana", "perWeek": 1,
                        "steps": ["Lehněte si na bok vedle lavice, loket dejte pod rameno.",
                                  "Horní nohu položte na lavici, na začátek kolenem, později kotníkem.",
                                  "Zvedněte pánev, až je tělo v přímce, spodní noha může viset nebo se přitáhnout k lavici.",
                                  "Vydržte, pak pomalu dolů a vyměňte stranu."],
                        "mistakes": ["Pánev klesá k zemi.", "Kotník na lavici dřív, než výdrž s kolenem jde bez bolesti."],
                        "caution": "Při bolesti v třísle nad 3 z 10 zůstaňte u verze s kolenem."},
    "pallof": {"name": "Pallof press", "area": "střed těla (antirotace)",
               "how": "Bokem ke gumě nebo kladce ji držte u hrudníku a vytlačte ruce před sebe. Trup se nesmí otočit.",
               "dose": "2 × 10 každá strana", "perWeek": 1,
               "steps": ["Uchyťte gumu ve výšce hrudníku a postavte se k ní bokem, krok od úchytu.",
                         "Gumu držte oběma rukama u hrudníku, kolena lehce pokrčená, břicho zpevněné.",
                         "Vytlačte ruce rovně před sebe a 2 sekundy vydržte, trup se nestáčí ke gumě.",
                         "Vraťte ruce k hrudníku. Po sérii se otočte druhým bokem."],
               "mistakes": ["Trup nebo pánev se natáčí ke gumě.", "Zvedání ramen."]},
    "sl_hops": {"name": "Poskoky na jedné noze", "area": "lýtko, kotník a koleno, pružnost",
                "how": "Nízké rytmické poskoky na jedné noze na místě, tiché a měkké dopady, koleno nad chodidlem.",
                "dose": "2 × 15 každá noha", "perWeek": 1,
                "steps": ["Stoupněte si na jednu nohu, druhou lehce pokrčte.",
                          "Poskakujte nízko na místě z kotníku, dopad na přední část chodidla.",
                          "Koleno míří nad chodidlo, pánev zůstává vodorovně.",
                          "Po sérii vyměňte nohu. Pokročilí poskakují dopředu a do stran."],
                "mistakes": ["Hlučný tvrdý dopad.", "Koleno padá dovnitř.", "Pánev klesá na straně volné nohy."],
                "caution": "Zařaďte až ve chvíli, kdy pogo poskoky snožmo nic nebolí. Při bolesti kosti vynechte."},
    "step_down": {"name": "Spouštění ze schodu (step-down)", "area": "kvadriceps a kontrola kolena",
                  "how": "Na schodu na jedné noze pomalu spusťte druhou patu k zemi a zpět nahoru. Koleno stojné nohy míří nad chodidlo.",
                  "dose": "3 × 10 každá noha", "perWeek": 1,
                  "steps": ["Stoupněte si jednou nohou na schod, druhá visí volně vedle.",
                            "Pomalu, asi 3 sekundy, pokrčujte stojnou nohu, až se pata volné nohy dotkne země.",
                            "Koleno stojné nohy míří nad druhý a třetí prst, pánev zůstává rovně.",
                            "Silou stojné nohy se vraťte nahoru."],
                  "mistakes": ["Koleno padá dovnitř.", "Pád dolů místo pomalého spouštění.", "Odraz z volné nohy."]},
    "sl_calf_slow": {"name": "Výpony na jedné noze s pomalým spouštěním", "area": "lýtko a Achillova šlacha",
                     "how": "Na hraně schodu se na jedné noze vytáhněte na špičku a 3 sekundy pomalu spouštějte patu pod úroveň schodu.",
                     "dose": "3 × 12 každá noha", "perWeek": 1,
                     "steps": ["Stoupněte si přední částí chodidla na hranu schodu, držte se zábradlí.",
                               "Vytáhněte se na jedné noze co nejvýš na špičku, koleno propnuté.",
                               "Patu spouštějte pomalu, aspoň 3 sekundy, až mírně pod úroveň schodu.",
                               "Po sérii vyměňte nohu. Když je to snadné, přidejte batoh nebo činku."],
                     "mistakes": ["Rychlé houpání nahoru a dolů.", "Malý rozsah pohybu.", "Přenášení váhy na ruce."]},
    "side_plank_abd": {"name": "Boční plank s unožením", "area": "střed těla a hýždě",
                       "how": "Boční plank s oporou o loket a horní nohu zvedněte a držte nad spodní. Tělo v přímce.",
                       "dose": "2 × 30 s každá strana", "perWeek": 1,
                       "steps": ["Lehněte si na bok, loket pod rameno, nohy natažené na sobě.",
                                 "Zvedněte pánev do přímky od hlavy po chodidla.",
                                 "Horní nohu propnutou zvedněte asi o 20–30 cm a držte ji tam.",
                                 "Vydržte, pak vyměňte stranu. Lehčí verze je se spodním kolenem na zemi."],
                       "mistakes": ["Pánev klesá.", "Horní noha jde dopředu místo nahoru.", "Tělo se přetáčí."]},
    # Running drills (běžecká abeceda). Names follow Czech athletics usage, the English drill
    # name is added where the Czech term is not settled.
    "skipink": {"name": "Skipink", "area": "běžecká technika",
                "how": "Rychlé nízké kroky s aktivním došlapem přes přední část chodidla pod tělo.",
                "dose": "2 × 20 m", "perWeek": 2,
                "steps": ["Dělejte drobné rychlé kroky s pomalým posunem vpřed.",
                          "Kolena se zvedají jen nízko a chodidlo došlapuje aktivně pod tělo přes přední část.",
                          "Kotník je pružný, trup vzpřímený a paže pracují rychle."],
                "mistakes": ["Došlap na patu nebo celé chodidlo.", "Příliš dlouhé kroky."]},
    "a_skip": {"name": "A-skip (liftink s poskokem)", "area": "běžecká technika",
               "how": "Poskočný krok s vysoko zvednutým kolenem švihové nohy a lehkým odrazem stojné nohy.",
               "dose": "2 × 20 m", "perWeek": 2,
               "steps": ["Jděte rytmem poskoku: pravá, pravá, levá, levá.",
                         "Při každém kroku zvedněte koleno švihové nohy do vodorovné polohy.",
                         "Stojná noha se lehce odráží z přední části chodidla a trup je vzpřímený.",
                         "Paže pracují jako při běhu, opačná ruka jde ke zvednutému koleni."],
               "mistakes": ["Záklon trupu.", "Došlap na patu."]},
    "heel_flicks": {"name": "Zakopávání", "area": "běžecká technika",
                    "how": "Klus s přitahováním pat k hýždím, kolena míří dolů a kroky jsou krátké.",
                    "dose": "2 × 20 m", "perWeek": 2,
                    "steps": ["Během lehkého klusu přitahujte paty k hýždím.",
                              "Kolena míří dolů, stehna se dopředu skoro nezvedají.",
                              "Kroky jsou krátké a rychlé s došlapem na přední část chodidla."],
                    "mistakes": ["Předklon trupu.", "Stehna jdou dopředu jako u liftinku."]},
    "b_skip": {"name": "B-skip (liftink s vykopnutím)", "area": "běžecká technika",
               "how": "Jako A-skip, jen se z horní polohy bérec vykopne dopředu a noha se aktivně stáhne pod tělo.",
               "dose": "2 × 20 m", "perWeek": 2,
               "steps": ["Začněte jako A-skip s vysoko zvednutým kolenem.",
                         "Z horní polohy vykopněte bérec dopředu, až je noha skoro propnutá.",
                         "Nohu pak aktivně stáhněte dolů a dozadu pod tělo, jako byste hrabali zem.",
                         "Došlap je na přední část chodidla pod těžištěm."],
               "mistakes": ["Došlap daleko před tělem.", "Záklon trupu."],
               "caution": "Při potížích se zadní stranou stehna ho zatím vynechte."},
    "straight_leg": {"name": "Předkopávání (běh s propnutými koleny)", "area": "běžecká technika",
                     "how": "Běh s propnutými koleny, nohy jdou střídavě dopředu jako nůžky a stahují zem pod tělo.",
                     "dose": "2 × 20 m", "perWeek": 2,
                     "steps": ["Běžte s propnutými koleny, nohy se střídají dopředu jako nůžky.",
                               "Chodidlo dopadá pod tělo na přední část a aktivně stahuje zem dozadu.",
                               "Trup je vzpřímený a paže pracují."],
                     "mistakes": ["Záklon trupu.", "Došlap daleko před těžištěm."],
                     "caution": "Při potížích se zadní stranou stehna ho zatím vynechte."},
    "bounding": {"name": "Odpichy", "area": "běžecká technika",
                 "how": "Dlouhé skoky střídavě z nohy na nohu s mohutnou prací paží.",
                 "dose": "2 × 20 m", "perWeek": 2,
                 "steps": ["Po krátkém rozběhu se odrážejte střídavě z jedné nohy na druhou do dlouhých skoků.",
                           "Koleno švihové nohy jde dopředu a nahoru, stojná noha se v odrazu propne.",
                           "Ve fázi letu držte tělo vzpřímeně a paže pracují mohutně.",
                           "Doskočte na přední část chodidla a hned se odrazte znovu."],
                 "mistakes": ["Doskok na patu.", "Příliš mnoho opakování hned na začátku."],
                 "caution": "Vynechte je při potížích s lýtkem nebo Achillovou šlachou, zatěžují je víc než běh."},
    "strides": {"name": "Stupňované rovinky", "area": "běžecká technika",
                "how": "Úsek 80 až 100 m s plynulým zrychlením do svižného, ale uvolněného tempa.",
                "dose": "4–6 × 80 m", "perWeek": 2,
                "steps": ["Po rozklusání si vyberte rovný úsek dlouhý 80 až 100 metrů.",
                          "Začněte volně a postupně zrychlujte zhruba na tempo závodu na 5 km.",
                          "Posledních 20 metrů povolte, běh má být uvolněný, ne sprint.",
                          "Zpět se vraťte chůzí nebo klusem a opakujte."],
                "mistakes": ["Plný sprint.", "Křeč v ramenou a obličeji."]},
}

# key → program. `match` = lower-case fragments of the body-map regions the program fits,
# `group` = "pain" (self-management of a complaint) or "performance" (core, running drills),
# `physio` = the Physiopedia page on the topic, linked for further reading only.
PHYSIO = "https://www.physio-pedia.com/"
PROGRAMS = [
    {"key": "achilles", "group": "pain", "physio": PHYSIO + "Achilles_Tendinopathy", "name": "Achillova šlacha", "weeks": 12,
     "match": ["achill"],
     "summary": "Postupně rostoucí zátěž šlachy výpony. Běhat se může dál, když bolest drží pravidlo níže.",
     "exercises": ["heel_raise_2", "heel_raise_1", "ecc_straight", "ecc_bent", "hops"],
     "evidence": "Zatěžování šlachy s průběžným sledováním bolesti vedlo ke zlepšení a pokračování v běhu mu neuškodilo "
                 "(Silbernagel et al., 2007). Spouštění paty ze schodu 3 × 15 dvakrát denně po 12 týdnů (Alfredson et al., 1998).",
     "refs": ["Silbernagel et al., 2007", "Alfredson et al., 1998"], "assumption": "Pořadí a poskoky až v závěru jsou pracovní předpoklad."},
    {"key": "calf", "group": "pain", "physio": PHYSIO + "Calf_Strain", "name": "Lýtko", "weeks": 6,
     "match": ["lýtk", "lytk", "gastrocnem", "soleus", "bérec"],
     "summary": "Síla lýtka propnutým i pokrčeným kolenem, na závěr pružnost poskoky.",
     "exercises": ["heel_raise_2", "heel_raise_1", "seated_calf", "hops"],
     "evidence": "Výpony vsedě, na dvou a na jedné noze a poskoky zatěžují lýtko a šlachu postupně víc, od půl násobku po sedminásobek tělesné hmotnosti "
                 "(Baxter et al., 2021).",
     "refs": ["Baxter et al., 2021"], "assumption": "Dávkování je pracovní předpoklad produktového týmu."},
    {"key": "plantar", "group": "pain", "physio": PHYSIO + "Plantar_Fasciitis", "name": "Plantární fascie (pata)", "weeks": 12,
     "match": ["plantár", "plantar", "pata"],
     "summary": "Výpon s ručníkem pod prsty s velkou zátěží, pomalu, obden.",
     "exercises": ["towel_raise"],
     "evidence": "Výpon na jedné noze s ručníkem pod prsty obden po 3 měsíce: 3 × 12 opakování s maximální zátěží, po 2 týdnech 4 × 10, "
                 "od 5. týdne 5 × 8 (Rathleff et al., 2015). Po 3 měsících byl výsledek lepší než po samotném protahování.",
     "refs": ["Rathleff et al., 2015"], "assumption": None},
    {"key": "knee", "group": "pain", "physio": PHYSIO + "Patellofemoral_Pain_Syndrome", "name": "Koleno vpředu", "weeks": 6,
     "match": ["kolen", "patel", "kvadricepsová šlacha"],
     "summary": "Posílení kyčle a kolena dohromady.",
     "exercises": ["side_abd", "clamshell", "bridge", "wall_squat", "step_up", "knee_ext"],
     "evidence": "U bolesti kolena vpředu odborný konsenzus doporučuje cvičení, nejlépe kombinaci cviků na kyčel a na koleno "
                 "(Collins et al., 2018). Kombinace ulevila od bolesti víc než samotné cviky na koleno (van der Heijden et al., 2016).",
     "refs": ["Collins et al., 2018", "van der Heijden et al., 2016"],
     "assumption": "Dávkování je pracovní předpoklad. Při bolesti přímo na šlaše pod čéškou se postup liší, poraďte se s fyzioterapeutem."},
    {"key": "itb", "group": "pain", "physio": PHYSIO + "Iliotibial_Band_Syndrome", "name": "IT pás a vnější strana kolena", "weeks": 6,
     "match": ["iliotib", "it band", "it pás", "hýžd", "glute"],
     "summary": "Síla a vytrvalost abduktorů kyčle, kontrola pánve na jedné noze.",
     "exercises": ["side_abd", "pelvic_drop", "clamshell", "sl_squat"],
     "evidence": "Běžci s bolestí IT pásu měli slabší abduktory kyčle a po 6 týdnech jejich posilování se 22 z 24 vrátilo k běhu bez bolesti "
                 "(Fredericson et al., 2000). Posilování abduktorů je nejčastější složkou úspěšné léčby (Sanchez-Alvarado et al., 2024).",
     "refs": ["Fredericson et al., 2000", "Sanchez-Alvarado et al., 2024"], "assumption": "Dávkování je pracovní předpoklad."},
    {"key": "shin", "group": "pain", "physio": PHYSIO + "Medial_Tibial_Stress_Syndrome", "name": "Holeň", "weeks": 6,
     "match": ["holen", "holeň", "tibial"],
     "summary": "Úprava zátěže a postupné posílení lýtka a holeně.",
     "exercises": ["heel_raise_2", "heel_raise_1", "toe_raise", "balance"],
     "evidence": "Žádná léčba bolesti holeně zatím není spolehlivě prokázaná (Winters et al., 2013). Nejlogičtější je úprava zátěže, postupné zatěžování "
                 "a posílení lýtka (Winters, 2017).",
     "refs": ["Winters et al., 2013", "Winters, 2017"],
     "assumption": "Slabší důkazy, dávkování je pracovní předpoklad. Bolest přímo na kosti nechte posoudit."},
    {"key": "hamstring", "group": "pain", "physio": PHYSIO + "Hamstring_Strain", "name": "Zadní strana stehna", "weeks": 8,
     "match": ["hamstring", "zákolen", "sedací hrbol"],
     "summary": "Šetrný začátek výdrží v mostu, pak síla v prodloužení.",
     "exercises": ["bridge_iso", "bridge", "sl_rdl", "nordic"],
     "evidence": "Programy s nordickým hamstringem snížily výskyt zranění zadní strany stehna zhruba na polovinu (van Dyk et al., 2019), "
                 "přesnější rozbor ale účinek za jistý nepovažuje (Impellizzeri et al., 2021). Mrtvý tah na jedné noze zlepšil sílu stejně jako nordický "
                 "hamstring (Behan et al., 2024).",
     "refs": ["van Dyk et al., 2019", "Impellizzeri et al., 2021", "Behan et al., 2024"],
     "assumption": "Nordický hamstring až bez bolesti. Dávkování je pracovní předpoklad."},
    {"key": "groin", "group": "pain", "physio": PHYSIO + "Adductor_Related_Groin_Pain", "name": "Tříslo (adduktory)", "weeks": 8,
     "match": ["třísl", "addukt", "groin"],
     "summary": "Postupně rostoucí zátěž adduktorů: výdrž, pohyb a nakonec kodaňský plank.",
     "exercises": ["add_squeeze", "side_adduction", "copenhagen", "side_plank", "balance"],
     "evidence": "U dlouhodobé bolesti třísla z adduktorů vedl aktivní posilovací program v randomizované studii k návratu ke sportu bez bolesti "
                 "mnohem častěji než pasivní fyzioterapie (Hölmich et al., 1999). Program s kodaňským plankem snížil výskyt potíží s tříslem "
                 "zhruba o 40 % (Harøy et al., 2019).",
     "refs": ["Hölmich et al., 1999", "Harøy et al., 2019"],
     "assumption": "Studie zkoumaly hlavně fotbalisty, dávkování pro běžce je pracovní předpoklad. Bolest v třísle bez vazby na pohyb nechte posoudit."},
    {"key": "lower_abs", "group": "pain", "physio": PHYSIO + "Groin_Pain", "name": "Dolní břicho (úpon břišních svalů)", "weeks": 8,
     "match": ["břiš", "abdom"],
     "summary": "Postupně rostoucí zátěž břišních svalů a třísla: výdrže, pak pohyb, nakonec plank.",
     "exercises": ["pelvic_tilt", "curl_up", "dead_bug", "add_squeeze", "side_plank", "plank"],
     "evidence": "Bolest v podbřišku a třísle se u sportovců dělí podle místa na adduktorovou, iliopsoatickou, inguinální a pubickou (Weir et al., 2015). "
                 "Aktivní posilovací program, který zahrnoval i cviky na břišní svaly, vedl u dlouhodobé bolesti třísla k návratu ke sportu bez bolesti "
                 "mnohem častěji než pasivní fyzioterapie (Hölmich et al., 1999).",
     "refs": ["Weir et al., 2015", "Hölmich et al., 1999"],
     "assumption": "Samostatná studie cvičení na úpon břišních svalů u běžců chybí, výběr cviků a dávkování jsou pracovní předpoklad. "
                   "Bolest u stydké kosti, při kašli nebo kýchnutí, nebo vyboulení v třísle nechte posoudit fyzioterapeutem nebo lékařem."},
    {"key": "durability", "group": "performance", "physio": PHYSIO + "Strength_Training",
     "name": "Runner's must-have: odolnost a prevence", "weeks": 26, "perWeek": 2,
     "match": [],
     "summary": "Šest měsíců, dvakrát týdně. Silová session A a session Odolnost B se střídají podle toho, co den unese. "
                "Opakování a zátěž rostou podle toho, jak se cítíte na konci tréninku.",
     "sessions": {"A": ["pogo_hops", "monster_walk", "bulgarian_ss", "rdl", "seated_calf", "copenhagen_hold", "pallof"],
                  "B": ["sl_hops", "step_down", "pelvic_drop", "sl_rdl", "sl_calf_slow", "toe_raise", "side_plank_abd", "dead_bug"]},
     "exercises": ["pogo_hops", "monster_walk", "bulgarian_ss", "rdl", "seated_calf", "copenhagen_hold", "pallof",
                   "sl_hops", "step_down", "pelvic_drop", "sl_rdl", "sl_calf_slow", "toe_raise", "side_plank_abd", "dead_bug"],
     "evidence": "Silový trénink snížil výskyt sportovních zranění na méně než třetinu a přetěžovacích zhruba na polovinu "
                 "(Lauersen et al., 2014), s větším účinkem při větším objemu a intenzitě (Lauersen et al., 2018). U vytrvalců zlepšuje "
                 "ekonomiku běhu, nejlépe těžká zátěž dvakrát až třikrát týdně (Blagrove et al., 2018; Rønnestad & Mujika, 2014). "
                 "Šlachy se přizpůsobují vysoké zátěži s pomalým a delším zatížením (Bohm et al., 2015). Progrese podle pocitu na konci "
                 "tréninku vychází ze škály náročnosti a opakování v záloze (Foster et al., 2001; Helms et al., 2016). Těžká silová práce na nohy "
                 "zhoršuje tvrdý běh v následujících 24–48 hodinách, proto session A nepřijde den před ním (Doma et al., 2017). "
                 "Pokles pánve na straně volné nohy byl ze všech pohybových znaků nejvíc spojený s běžeckými zraněními (Bramah et al., 2018) "
                 "a osm týdnů funkčního posilování odtahovačů kyčle ho u běžců s bolestí holeně zmenšilo víc než samotná fyzioterapie "
                 "(Lashien et al., 2024), proto program obsahuje monster walk (session A) a spouštění pánve na schodu a boční plank s unožením (session B).",
     "refs": ["Lauersen et al., 2014", "Lauersen et al., 2018", "Blagrove et al., 2018", "Rønnestad & Mujika, 2014",
              "Bohm et al., 2015", "Foster et al., 2001", "Helms et al., 2016", "Doma et al., 2017",
              "Bramah et al., 2018", "Lashien et al., 2024"],
     "assumption": "Výběr cviků je od trenéra Došlapu, rozdělení do fází, rozsahy opakování a pravidla progrese jsou pracovní předpoklad "
                   "postavený na citovaných principech. Při bolesti platí pravidlo bolesti: do 5 z 10 při cviku, do rána odeznít."},
    {"key": "core", "group": "performance", "physio": PHYSIO + "Core_Stability", "name": "Core pro běžce", "weeks": 8,
     "match": [],
     "summary": "Vytrvalost svalů trupu a stabilita pánve, třikrát týdně po tréninku.",
     "exercises": ["plank", "side_plank", "dead_bug", "bird_dog", "bridge"],
     "evidence": "Osm týdnů cvičení středu těla třikrát týdně zlepšilo u vysokoškolských sportovců vytrvalost v planku, rovnováhu a ekonomiku běhu "
                 "(Hung et al., 2019). U rekreačních běžců zlepšilo přidání cviků na střed těla spojených s tréninkem nádechových svalů k intervalovému "
                 "tréninku ekonomiku a výkon v hodinovém běhu (Tong et al., 2016). Souhrn studií ale ukazuje velký účinek hlavně na vytrvalost trupu "
                 "a rovnováhu, na samotný sportovní výkon jen malý (Dong et al., 2023).",
     "refs": ["Hung et al., 2019", "Tong et al., 2016", "Dong et al., 2023"],
     "assumption": "Výběr cviků a dávkování je pracovní předpoklad, citované studie používaly jiné sestavy."},
    {"key": "drills", "group": "performance", "physio": PHYSIO + "Running_Biomechanics", "name": "Běžecká abeceda", "weeks": 8,
     "match": [],
     "summary": "Technická rozcvička před rychlejším tréninkem: skipinky, zakopávání, odpichy a rovinky.",
     "exercises": ["skipink", "a_skip", "heel_flicks", "b_skip", "straight_leg", "bounding", "strides"],
     "evidence": "Cviky abecedy napodobují části běžeckého kroku, s během ale nejsou totožné. A-skip, B-skip a zakopávání vedly k menšímu ohnutí "
                 "kotníku než běh a odpichy naopak k většímu výkonu v kotníku (Abran et al., 2024). A-skip zatěžoval lýtko méně než běh, "
                 "odpichy výrazně víc (Trowell et al., 2021). Že by abeceda sama zlepšila ekonomiku vytrvalostního běhu, zatím doloženo není.",
     "refs": ["Abran et al., 2024", "Trowell et al., 2021"],
     "assumption": "Výběr cviků, pořadí a dávkování vychází z trenérské praxe, ne z výzkumu. Zařaďte ji po rozklusání, ne na úplný začátek."},
]
PROGRAM_BY_KEY = {p["key"]: p for p in PROGRAMS}

REFERENCES = {
    "Lauersen et al., 2014": "Lauersen, J. B., Bertelsen, D. M., & Andersen, L. B. (2014). The effectiveness of exercise interventions to prevent sports injuries: A systematic review and meta-analysis of randomised controlled trials. British Journal of Sports Medicine, 48(11), 871–877.",
    "Lauersen et al., 2018": "Lauersen, J. B., Andersen, T. E., & Andersen, L. B. (2018). Strength training as superior, dose-dependent and safe prevention of acute and overuse sports injuries: A systematic review, qualitative analysis and meta-analysis. British Journal of Sports Medicine, 52(24), 1557–1563.",
    "Blagrove et al., 2018": "Blagrove, R. C., Howatson, G., & Hayes, P. R. (2018). Effects of strength training on the physiological determinants of middle- and long-distance running performance: A systematic review. Sports Medicine, 48(5), 1117–1149.",
    "Rønnestad & Mujika, 2014": "Rønnestad, B. R., & Mujika, I. (2014). Optimizing strength training for running and cycling endurance performance: A review. Scandinavian Journal of Medicine & Science in Sports, 24(4), 603–612.",
    "Bohm et al., 2015": "Bohm, S., Mersmann, F., & Arampatzis, A. (2015). Human tendon adaptation in response to mechanical loading: A systematic review and meta-analysis of exercise intervention studies on healthy adults. Sports Medicine - Open, 1(1), 7.",
    "Foster et al., 2001": "Foster, C., Florhaug, J. A., Franklin, J., Gottschall, L., Hrovatin, L. A., Parker, S., Doleshal, P., & Dodge, C. (2001). A new approach to monitoring exercise training. Journal of Strength and Conditioning Research, 15(1), 109–115.",
    "Helms et al., 2016": "Helms, E. R., Cronin, J., Storey, A., & Zourdos, M. C. (2016). Application of the repetitions in reserve-based rating of perceived exertion scale for resistance training. Strength and Conditioning Journal, 38(4), 42–49.",
    "Doma et al., 2017": "Doma, K., Deakin, G. B., & Bentley, D. J. (2017). Implications of impaired endurance performance following single bouts of resistance training: An alternate concurrent training perspective. Sports Medicine, 47(11), 2187–2200.",
    "Bramah et al., 2018": "Bramah, C., Preece, S. J., Gill, N., & Herrington, L. (2018). Is there a pathological gait associated with common soft tissue running injuries? The American Journal of Sports Medicine, 46(12), 3023–3031.",
    "Lashien et al., 2024": "Lashien, S. A., et al. (2024). Effect of hip abductors training on pelvic drop and knee valgus in runners with medial tibial stress syndrome: A randomized controlled trial. Journal of Orthopaedic Surgery and Research, 19.",
    "Weir et al., 2015": "Weir, A., Brukner, P., Delahunt, E., Ekstrand, J., Griffin, D., Khan, K. M., Lovell, G., Meyers, W. C., Muschaweck, U., Orchard, J., Paajanen, H., Philippon, M., Reboul, G., Robinson, P., Schache, A. G., Schilders, E., Serner, A., Silvers, H., Thorborg, K., … Hölmich, P. (2015). Doha agreement meeting on terminology and definitions in groin pain in athletes. British Journal of Sports Medicine, 49(12), 768–774.",
    "Hölmich et al., 1999": "Hölmich, P., Uhrskou, P., Ulnits, L., Kanstrup, I.-L., Nielsen, M. B., Bjerg, A. M., & Krogsgaard, K. (1999). Effectiveness of active physical training as treatment for long-standing adductor-related groin pain in athletes: Randomised trial. The Lancet, 353(9151), 439–443.",
    "Harøy et al., 2019": "Harøy, J., Clarsen, B., Wiger, E. G., Øyen, M. G., Serner, A., Thorborg, K., Hölmich, P., Andersen, T. E., & Bahr, R. (2019). The Adductor Strengthening Programme prevents groin problems among male football players: A cluster-randomised controlled trial. British Journal of Sports Medicine, 53(3), 150–157.",
    "Alfredson et al., 1998": "Alfredson, H., Pietilä, T., Jonsson, P., & Lorentzon, R. (1998). Heavy-load eccentric calf muscle training for the treatment of chronic Achilles tendinosis. The American Journal of Sports Medicine, 26(3), 360–366.",
    "Silbernagel et al., 2007": "Silbernagel, K. G., Thomeé, R., Eriksson, B. I., & Karlsson, J. (2007). Continued sports activity, using a pain-monitoring model, during rehabilitation in patients with Achilles tendinopathy. The American Journal of Sports Medicine, 35(6), 897–906.",
    "Baxter et al., 2021": "Baxter, J. R., Corrigan, P., Hullfish, T. J., O'Rourke, P., & Silbernagel, K. G. (2021). Exercise progression to incrementally load the Achilles tendon. Medicine & Science in Sports & Exercise, 53(1), 124–130.",
    "Rathleff et al., 2015": "Rathleff, M. S., Mølgaard, C. M., Fredberg, U., Kaalund, S., Andersen, K. B., Jensen, T. T., Aaskov, S., & Olesen, J. L. (2015). High-load strength training improves outcome in patients with plantar fasciitis. Scandinavian Journal of Medicine & Science in Sports, 25(3), e292–e300.",
    "Collins et al., 2018": "Collins, N. J., Barton, C. J., van Middelkoop, M., et al. (2018). 2018 Consensus statement on exercise therapy and physical interventions to treat patellofemoral pain. British Journal of Sports Medicine, 52(18), 1170–1178.",
    "van der Heijden et al., 2016": "van der Heijden, R. A., Lankhorst, N. E., van Linschoten, R., Bierma-Zeinstra, S. M., & van Middelkoop, M. (2016). Exercise for treating patellofemoral pain syndrome: An abridged version of Cochrane systematic review. European Journal of Physical and Rehabilitation Medicine, 52(1), 110–133.",
    "Fredericson et al., 2000": "Fredericson, M., Cookingham, C. L., Chaudhari, A. M., Dowdell, B. C., Oestreicher, N., & Sahrmann, S. A. (2000). Hip abductor weakness in distance runners with iliotibial band syndrome. Clinical Journal of Sport Medicine, 10(3), 169–175.",
    "Sanchez-Alvarado et al., 2024": "Sanchez-Alvarado, A., Bokil, C., Cassel, M., & Engel, T. (2024). Effects of conservative treatment strategies for iliotibial band syndrome on pain and function in runners: A systematic review. Frontiers in Sports and Active Living, 6.",
    "Winters et al., 2013": "Winters, M., Eskes, M., Weir, A., Moen, M. H., Backx, F. J., & Bakker, E. W. (2013). Treatment of medial tibial stress syndrome: A systematic review. Sports Medicine, 43(12), 1315–1333.",
    "Winters, 2017": "Winters, M. (2017). Medial tibial stress syndrome: Diagnosis, treatment and outcome assessment (PhD Academy Award). British Journal of Sports Medicine.",
    "van Dyk et al., 2019": "van Dyk, N., Behan, F. P., & Whiteley, R. (2019). Including the Nordic hamstring exercise in injury prevention programmes halves the rate of hamstring injuries. British Journal of Sports Medicine, 53(21), 1362–1370.",
    "Impellizzeri et al., 2021": "Impellizzeri, F. M., McCall, A., & van Smeden, M. (2021). Why methods matter in a meta-analysis: A reappraisal showed inconclusive injury preventive effect of Nordic hamstring exercise. Journal of Clinical Epidemiology.",
    "Behan et al., 2024": "Behan, F. P., et al. (2024). Implementing hamstring injury prevention programmes remotely: A randomised proof of concept trial. BMJ Open Sport & Exercise Medicine.",
    "Warden et al., 2014": "Warden, S. J., Davis, I. S., & Fredericson, M. (2014). Management and prevention of bone stress injuries in long-distance runners. Journal of Orthopaedic & Sports Physical Therapy, 44(10), 749–765.",
    "Hung et al., 2019": "Hung, K.-C., Chung, H.-W., Yu, C. C.-W., Lai, H.-C., & Sun, F.-H. (2019). Effects of 8-week core training on core endurance and running economy. PLoS ONE, 14(3), e0213158.",
    "Tong et al., 2016": "Tong, T. K., McConnell, A. K., Lin, H., Nie, J., Zhang, H., & Wang, J. (2016). \"Functional\" inspiratory and core muscle training enhances running performance and economy. Journal of Strength and Conditioning Research, 30(10), 2942–2951.",
    "Dong et al., 2023": "Dong, K., Yu, T., & Chun, B. (2023). Effects of core training on sport-specific performance of athletes: A meta-analysis of randomized controlled trials. Behavioral Sciences, 13(2), 148.",
    "Abran et al., 2024": "Abran, G., et al. (2024). A comparison of foot and ankle biomechanics during running drills and distance running. Sports Biomechanics.",
    "Trowell et al., 2021": "Trowell, D., et al. (2021). A comparison of plantarflexor musculotendon unit output between plyometric exercises and running. Journal of Science and Medicine in Sport.",
}


def programs_for_regions(regions: list[str]) -> list[str]:
    """Program keys that fit the marked pain regions, most marked first."""
    hits: dict[str, int] = {}
    for reg in regions:
        r = (reg or "").lower()
        for p in PROGRAMS:
            if any(m in r for m in p["match"]):
                hits[p["key"]] = hits.get(p["key"], 0) + 1
    return sorted(hits, key=lambda k: -hits[k])


def _exercise_links() -> dict:
    """Exercise id → the Physiopedia pages of the programs it belongs to (further reading)."""
    out: dict[str, list] = {}
    for p in PROGRAMS:
        for x in p["exercises"]:
            if not any(lk["url"] == p["physio"] for lk in out.setdefault(x, [])):
                out[x].append({"url": p["physio"], "topic": p["name"]})
    return out


def library() -> dict:
    links = _exercise_links()
    ex = {k: {**v, "links": links.get(k, [])} for k, v in EXERCISES.items()}
    from . import durability as DU
    progs = [({**p, "phases": [{"key": x[2], "name": x[3], "goal": x[4], "from": x[0], "to": x[1], "rpe": x[5]} for x in DU.PHASES],
               "sessionLabels": {k: v["label"] for k, v in DU.SESSIONS.items()},
               "sessionDoses": {k: {x["id"]: x["dose"] for x in DU.session_plan(k, 1, 0, False)} for k in DU.SESSIONS}}
              if p["key"] == "durability" else p) for p in PROGRAMS]
    return {"exercises": ex, "programs": progs, "painRule": PAIN_RULE, "references": REFERENCES, "reviewed": False,
            "source": "Texty cviků a ilustrace jsou vlastní. Physiopedia slouží jen jako odkaz na další čtení."}
