"""Feedback railway#116 — ready-made exercise programs for the most common running
problems, which the runner can start on their own, and the exercise library a runner
builds their own session from.

No free exercise database fits a commercial physio product as it is: free-exercise-db
(Unlicense) covers gym exercises and its images have no known licence, wger data are
Creative Commons per entry and mostly gym exercises, Physiopedia is non-commercial. So
the exercises and the programs are written here, from published protocols, each with its
source. Doses that no source fixes are the product team's working assumptions and are
marked as such (`assumption`). The programs are for self-management of mild complaints,
not a replacement for an examination; they wait for review by a Došlap physiotherapist
(`reviewed` = False until then).

Pain rule for every program: pain up to 5/10 during an exercise is acceptable, it must
settle by the next morning and must not grow from week to week (Silbernagel et al.,
2007); bone pain follows the complete absence of pain instead (Warden et al., 2014).
"""

PAIN_RULE = ("Bolest při cvičení do 5 z 10 je v pořádku, do druhého rána musí odeznít a nesmí týden od týdne růst. "
             "Když roste nebo je ráno horší, uberte počet opakování.")

# id → exercise. `how` = execution in two or three short sentences, `dose` = default dose,
# `steps` = numbered execution for the exercise detail, `mistakes` = the common faults to
# watch, `caution` = when to leave the exercise out. All texts are written for Došlap from
# the cited protocols and general exercise technique; no text or image is taken over from
# Physiopedia (CC BY-NC-SA, non-commercial), which the detail only links to.
EXERCISES = {
    "heel_raise_2": {"name": "Výpony na obou nohách", "area": "lýtko a Achillova šlacha",
                     "how": "Stoupněte si na špičky plynule nahoru a pomalu dolů, kolena propnutá. Držte se lehce zdi.",
                     "dose": "3 × 15", "perWeek": 7,
                     "steps": ["Postavte se na šířku pánve, prsty dopředu, a jednou rukou se lehce opřete o zeď.",
                               "Za 2 sekundy se zvedněte co nejvýš na špičky, váha jde přes palec a druhý prst.",
                               "Nahoře krátce vydržte a za 3 sekundy se spusťte zpět na paty.",
                               "Kolena zůstávají propnutá a tělo se nenaklání dopředu."],
                     "mistakes": ["Rychlé houpání nahoru a dolů bez kontroly.", "Vytáčení kotníků ven, kdy váha přejde na malíček."]},
    "heel_raise_1": {"name": "Výpony na jedné noze", "area": "lýtko a Achillova šlacha",
                     "how": "Na jedné noze nahoru za 2 s, nahoře krátká výdrž, dolů za 3 s. Postupně přidejte batoh se zátěží.",
                     "dose": "3 × 15", "perWeek": 7,
                     "steps": ["Stoupněte si na jednu nohu, druhou pokrčte a prsty ruky se lehce dotkněte zdi.",
                               "Za 2 sekundy se zvedněte na špičku a nahoře vydržte 1 sekundu.",
                               "Za 3 sekundy se spusťte až na patu.",
                               "Když zvládnete 3 × 15 bez potíží, přidejte batoh se zátěží."],
                     "mistakes": ["Opírání o zeď celou vahou.", "Neúplný rozsah, kdy pata nejde naplno nahoru ani dolů."]},
    "ecc_straight": {"name": "Spouštění paty ze schodu, propnuté koleno", "area": "Achillova šlacha",
                     "how": "Na hraně schodu se zvedněte na obou nohách, pak se pomalu spouštějte jen na bolavé noze pod úroveň schodu. Nahoru zase oběma.",
                     "dose": "3 × 15, 2× denně", "perWeek": 14,
                     "steps": ["Stoupněte si přední částí chodidel na hranu schodu tak, aby paty přesahovaly.",
                               "Zvedněte se na obou nohách na špičky.",
                               "Přeneste váhu na bolavou nohu a za 3 sekundy spusťte patu pod úroveň schodu, koleno zůstává propnuté.",
                               "Zpět nahoru se vraťte oběma nohama nebo s pomocí zdravé nohy."],
                     "mistakes": ["Zvedání nahoru jen bolavou nohou, cvik pracuje hlavně při spouštění.", "Rychlé spadnutí dolů bez brzdění."]},
    "ecc_bent": {"name": "Spouštění paty ze schodu, pokrčené koleno", "area": "Achillova šlacha a soleus",
                 "how": "Stejně jako se spouštěním paty, jen s mírně pokrčeným kolenem, aby pracoval hlubší lýtkový sval.",
                 "dose": "3 × 15, 2× denně", "perWeek": 14,
                 "steps": ["Postavte se na hranu schodu stejně jako u spouštění s propnutým kolenem.",
                           "Zvedněte se na obou nohách na špičky a mírně pokrčte kolena.",
                           "S pokrčeným kolenem se na bolavé noze za 3 sekundy spusťte pod úroveň schodu.",
                           "Nahoru se vraťte oběma nohama."],
                 "mistakes": ["Propínání kolena během spouštění.", "Přenášení váhy do zdi místo do chodidla."]},
    "seated_calf": {"name": "Výpony vsedě se zátěží", "area": "soleus (hluboké lýtko)",
                    "how": "Vsedě s koleny v pravém úhlu a se zátěží na stehnech zvedejte paty. Pomalu nahoru i dolů.",
                    "dose": "3 × 12", "perWeek": 3,
                    "steps": ["Sedněte si na židli s koleny v pravém úhlu a chodidly na zemi.",
                              "Na stehna těsně nad koleny položte zátěž, třeba batoh nebo činku.",
                              "Zvedněte paty co nejvýš a nahoře vydržte 1 sekundu.",
                              "Pomalu je spusťte zpět na zem."],
                    "mistakes": ["Příliš lehká zátěž, poslední opakování mají být náročná.", "Tlačení rukama do stehen místo práce lýtek."]},
    "hops": {"name": "Poskoky na místě", "area": "lýtko a šlacha, pružnost",
             "how": "Lehké rytmické poskoky na obou nohách, později na jedné. Jen když při výponech nic nebolí.",
             "dose": "3 × 20 s", "perWeek": 3,
             "steps": ["Postavte se na šířku pánve s volnými pažemi.",
                       "Poskakujte lehce a rytmicky z přední části chodidel, paty se země skoro nedotýkají.",
                       "Kolena jsou jen mírně pokrčená a odraz jde hlavně z kotníků.",
                       "Když to jde bez bolesti, zkuste poskoky na jedné noze."],
             "mistakes": ["Hlučné dopady s propadnutím do kolen.", "Začátek poskoků ve chvíli, kdy ještě bolí výpony."],
             "caution": "Zařaďte je až ve chvíli, kdy výpony na jedné noze nebolí."},
    "towel_raise": {"name": "Výpon na jedné noze s ručníkem pod prsty", "area": "plantární fascie",
                    "how": "Srolovaný ručník pod prsty, aby byly zvednuté. Nahoru 3 s, nahoře 2 s výdrž, dolů 3 s. Zátěž přidejte batohem.",
                    "dose": "3 × 12 (max. zátěž na 12 opakování)", "perWeek": 3,
                    "steps": ["Srolujte ručník, položte ho na zem a opřete o něj prsty jedné nohy, aby byly zvednuté.",
                              "Stoupněte si na tuto nohu, druhou pokrčte a rukou se lehce opřete.",
                              "Za 3 sekundy se zvedněte, nahoře vydržte 2 sekundy a za 3 sekundy se spusťte.",
                              "Zátěž volte tak, abyste zvládli právě 12 opakování, a přidávejte ji batohem."],
                    "mistakes": ["Prsty sklouznou z ručníku.", "Příliš rychlé tempo nahoru i dolů."]},
    "side_abd": {"name": "Unožování vleže na boku", "area": "hýžďové svaly (abduktory kyčle)",
                 "how": "Vleže na boku zvedněte horní propnutou nohu mírně za tělo, špička dopředu. Pomalu dolů.",
                 "dose": "3 × 15", "perWeek": 4,
                 "steps": ["Lehněte si na bok, spodní nohu můžete pokrčit, horní je propnutá v linii s tělem.",
                           "Horní nohu zvedněte mírně za osu těla, špička míří dopředu, ne ke stropu.",
                           "Jděte jen do výšky, kterou zvládnete bez překlopení pánve, a nahoře vydržte 1 sekundu.",
                           "Pomalu nohu spusťte."],
                 "mistakes": ["Noha jde před tělo a práci přebírá přední strana stehna.", "Pánev se překlápí dozadu."]},
    "clamshell": {"name": "Mušle", "area": "hýžďové svaly",
                  "how": "Vleže na boku s pokrčenými koleny a spojenými chodidly otvírejte horní koleno, pánev se neotáčí. Zesílíte gumou.",
                  "dose": "3 × 15", "perWeek": 4,
                  "steps": ["Lehněte si na bok, kyčle a kolena pokrčte a chodidla dejte k sobě.",
                            "Horní koleno otevřete nahoru, chodidla zůstávají spojená.",
                            "Pánev se nepřetáčí dozadu, pro kontrolu na ni položte ruku.",
                            "Pomalu zavřete. Ztížíte si to gumou kolem stehen nad koleny."],
                  "mistakes": ["Přetáčení pánve dozadu, aby koleno šlo výš.", "Rychlé švihání kolenem."]},
    "bridge": {"name": "Most", "area": "hýždě a zadní strana stehen",
               "how": "Vleže na zádech s pokrčenými koleny zvedněte pánev do přímky, nahoře 2 s výdrž. Pokročile na jedné noze.",
               "dose": "3 × 12", "perWeek": 4,
               "steps": ["Lehněte si na záda, kolena pokrčte, chodidla dejte na šířku pánve a ruce podél těla.",
                         "Zatlačte patami do země a zvedněte pánev, až jsou kolena, kyčle a ramena v jedné linii.",
                         "Nahoře vydržte 2 sekundy se zpevněnými hýžděmi.",
                         "Pomalu spusťte pánev na zem. Pokročilejší verze je na jedné noze."],
               "mistakes": ["Prohýbání v bedrech místo zvednutí silou hýždí.", "Kolena padají od sebe nebo k sobě."]},
    "wall_squat": {"name": "Dřep u zdi", "area": "kvadriceps",
                   "how": "Zády u zdi sjeďte do hloubky, která nebolí, a vydržte. Kolena míří nad špičky.",
                   "dose": "5 × 30 s", "perWeek": 4,
                   "steps": ["Opřete se zády o zeď, chodidla dejte kousek před sebe na šířku pánve.",
                             "Sjeďte po zdi do hloubky, která nebolí, nejvýš do pravého úhlu v kolenou.",
                             "Kolena míří nad druhý prst a váha je na celých chodidlech.",
                             "Vydržte a pak se po zdi vysuňte zpět nahoru."],
                   "mistakes": ["Kolena padají dovnitř.", "Zadržování dechu během výdrže."]},
    "step_up": {"name": "Výstup na schod", "area": "kvadriceps a hýždě",
                "how": "Vystupte na schod jednou nohou a pomalu sestupte zpět. Koleno nepadá dovnitř, pánev zůstává rovně.",
                "dose": "3 × 10 každá noha", "perWeek": 3,
                "steps": ["Postavte se před schod nebo stabilní bednu a jednu nohu na něj položte celým chodidlem.",
                          "Přeneste váhu na horní nohu a vystupte nahoru, spodní noha jen přisune.",
                          "Pomalu sestupte zpět a pohyb brzděte horní nohou.",
                          "Koleno míří nad špičku a pánev zůstává vodorovně."],
                "mistakes": ["Odraz spodní nohou, který práci ubere.", "Koleno padá dovnitř."]},
    "knee_ext": {"name": "Předkopávání vsedě", "area": "kvadriceps",
                 "how": "Vsedě propněte koleno proti odporu gumy nebo zátěže na kotníku a pomalu povolte.",
                 "dose": "3 × 12", "perWeek": 3,
                 "steps": ["Sedněte si na židli a kolem kotníku dejte zátěž nebo gumu uchycenou za nohu židle.",
                           "Za 2 sekundy propněte koleno do natažení.",
                           "Nahoře vydržte 1 sekundu a za 3 sekundy povolte."],
                 "mistakes": ["Švihání nohou.", "Zaklánění trupu, které pomáhá zvednout zátěž."]},
    "pelvic_drop": {"name": "Spouštění pánve na schodu", "area": "střední hýžďový sval",
                    "how": "Stůjte bokem na schodu na jedné noze, druhou nechte volně viset. Spusťte pánev na volné straně dolů a zvedněte ji zpět silou stojné kyčle.",
                    "dose": "3 × 15", "perWeek": 4,
                    "steps": ["Stoupněte si bokem na schod na jednu nohu, druhá visí volně přes okraj.",
                              "Stojná noha zůstává propnutá a ramena v klidu.",
                              "Spusťte pánev na straně volné nohy o pár centimetrů dolů.",
                              "Silou stojné kyčle ji zvedněte zpět nad vodorovnou úroveň."],
                    "mistakes": ["Pokrčování stojného kolena.", "Naklánění trupu do strany."]},
    "sl_squat": {"name": "Dřep na jedné noze", "area": "kyčel a koleno, kontrola",
                 "how": "Pomalý mělký dřep na jedné noze před zrcadlem, koleno nad špičkou, pánev rovně.",
                 "dose": "3 × 8", "perWeek": 3,
                 "steps": ["Stoupněte si na jednu nohu, nejlépe před zrcadlo, ruce dejte před tělo.",
                           "Pomalu se spouštějte do mělkého dřepu, jako byste si chtěli sednout.",
                           "Koleno míří nad druhý prst a pánev zůstává rovně.",
                           "Vraťte se nahoru. Hloubku přidávejte, jen když udržíte kontrolu."],
                 "mistakes": ["Koleno padá dovnitř.", "Pánev klesá na straně volné nohy."]},
    "toe_raise": {"name": "Zvedání špiček", "area": "přední sval holeně",
                  "how": "Zády u zdi s patami kousek od ní zvedejte špičky co nejvýš a pomalu dolů.",
                  "dose": "3 × 20", "perWeek": 4,
                  "steps": ["Opřete se zády o zeď, paty dejte asi na délku chodidla od ní.",
                            "Zvedněte špičky co nejvýš k holením, paty zůstávají na zemi.",
                            "Pomalu je spusťte zpět."],
                  "mistakes": ["Rychlé plácání špičkami o zem.", "Odlepování zad od zdi."]},
    "balance": {"name": "Stoj na jedné noze", "area": "kotník a stabilita",
                "how": "Stoj na jedné noze s mírně pokrčeným kolenem. Ztížíte zavřenýma očima nebo na polštáři.",
                "dose": "3 × 30 s", "perWeek": 5,
                "steps": ["Postavte se na jednu nohu s mírně pokrčeným kolenem.",
                          "Pánev držte rovně a dívejte se před sebe.",
                          "Když 30 sekund zvládnete snadno, zavřete oči nebo se postavte na polštář."],
                "mistakes": ["Zamčené propnuté koleno.", "Opírání volné nohy o stojnou."]},
    "nordic": {"name": "Nordický hamstring", "area": "zadní strana stehen",
               "how": "Vkleče s fixovanými kotníky se pomalu naklánějte dopředu s rovnými zády, brzděte zadní stranou stehen, pak se zachyťte rukama.",
               "dose": "2–3 × 5–8", "perWeek": 2,
               "steps": ["Klekněte si na měkkou podložku, kotníky vám přidrží partner nebo je zapřete pod těžký nábytek.",
                         "Tělo držte rovně od kolen po hlavu a ruce dejte před hrudník.",
                         "Pomalu se naklánějte dopředu a pohyb brzděte zadní stranou stehen co nejdéle.",
                         "Když už pád neudržíte, zachyťte se rukama a odtlačte se zpět nahoru."],
               "mistakes": ["Předklon v kyčlích místo rovného těla.", "Rychlý pád bez brzdění."],
               "caution": "Zařaďte ho až ve chvíli, kdy zadní strana stehna při běžné chůzi a mostu nebolí."},
    "sl_rdl": {"name": "Rumunský mrtvý tah na jedné noze", "area": "hamstring a hýždě",
               "how": "Na jedné noze s mírně pokrčeným kolenem se předkloňte s rovnými zády, druhá noha jde dozadu. Zpět silou hýždě.",
               "dose": "3 × 8 každá noha", "perWeek": 2,
               "steps": ["Stoupněte si na jednu nohu s mírně pokrčeným kolenem.",
                         "Předkloňte se v kyčlích s rovnými zády, volná noha jde dozadu v linii s trupem.",
                         "Jděte tak hluboko, až ucítíte natažení zadní strany stehna.",
                         "Zpět se narovnejte silou hýždě stojné nohy."],
               "mistakes": ["Kulatá záda.", "Pánev se otáčí ke straně volné nohy."]},
    "bridge_iso": {"name": "Výdrž v mostu na patách", "area": "hamstring, šetrný začátek",
                   "how": "Most s patami dál od těla, pánev nahoru a výdrž. Na začátek při bolesti zadní strany stehna.",
                   "dose": "5 × 30 s", "perWeek": 5,
                   "steps": ["Lehněte si na záda a paty položte dál od těla než u běžného mostu, špičky mohou jít nahoru.",
                             "Zvedněte pánev, až je tělo v přímce.",
                             "Vydržte a plynule dýchejte, pak pomalu dolů."],
                   "mistakes": ["Prohnutá bedra.", "Výdrž přes ostrou bolest v zadní straně stehna."]},
    # Core for runners (railway: new programs). Exercise choice follows Physiopedia's
    # core stability overview only as a list of common exercises; the wording is our own.
    "plank": {"name": "Plank na předloktích", "area": "střed těla",
              "how": "Opora na předloktích a špičkách, tělo v jedné přímce od hlavy po paty. Dýchejte a vydržte.",
              "dose": "3 × 20–40 s", "perWeek": 3,
              "steps": ["Opřete se o předloktí, lokty dejte pod ramena.",
                        "Natáhněte nohy dozadu a opřete se o špičky, začít můžete i na kolenou.",
                        "Tělo držte v jedné přímce od hlavy po paty, lehce zpevněte břicho a hýždě.",
                        "Dýchejte plynule a vydržte."],
              "mistakes": ["Propadlá bedra.", "Pánev vystrčená příliš vysoko."]},
    "side_plank": {"name": "Boční plank", "area": "střed těla",
                   "how": "Na boku s oporou o loket zvedněte pánev do přímky a vydržte. Lehčí verze je s pokrčenými koleny.",
                   "dose": "3 × 20 s každá strana", "perWeek": 3,
                   "steps": ["Lehněte si na bok, loket dejte pod rameno a nohy natáhněte na sebe.",
                             "Zvedněte pánev, až je tělo v přímce od hlavy po chodidla.",
                             "Vydržte a pak vyměňte stranu.",
                             "Lehčí verze je s pokrčenými koleny."],
                   "mistakes": ["Pánev klesá k zemi.", "Tělo se přetáčí dopředu nebo dozadu."]},
    "dead_bug": {"name": "Mrtvý brouk", "area": "střed těla",
                 "how": "Vleže na zádech pomalu natahujte opačnou ruku a nohu k zemi, bedra zůstávají na podložce.",
                 "dose": "3 × 8 každá strana", "perWeek": 3,
                 "steps": ["Lehněte si na záda, ruce natáhněte ke stropu, kyčle a kolena pokrčte do pravého úhlu.",
                           "Bedra přitiskněte k podložce.",
                           "Pomalu natáhněte jednu nohu a opačnou ruku k zemi, bedra se přitom nezvedají.",
                           "Vraťte se zpět a vystřídejte strany."],
                 "mistakes": ["Prohnutí beder při natažení nohy.", "Rychlé tempo bez kontroly."]},
    "bird_dog": {"name": "Bird dog (diagonála v kleku)", "area": "střed těla",
                 "how": "Na všech čtyřech natáhněte opačnou ruku a nohu do vodorovné polohy, záda zůstávají rovná.",
                 "dose": "3 × 8 každá strana", "perWeek": 3,
                 "steps": ["Klekněte si na všechny čtyři, dlaně pod rameny a kolena pod kyčlemi.",
                           "Záda držte rovně jako desku stolu.",
                           "Natáhněte jednu nohu dozadu a opačnou ruku dopředu do vodorovné polohy.",
                           "Vydržte 2 sekundy, vraťte se a vystřídejte strany."],
                 "mistakes": ["Zvedání nohy nad úroveň zad s prohnutím v bedrech.", "Přetáčení pánve do strany."]},
    # Running drills (běžecká abeceda). Names follow Czech athletics usage, the English drill
    # name is added where the Czech term is not settled.
    "skipink": {"name": "Skipink", "area": "běžecká technika",
                "how": "Rychlé nízké kroky s aktivním došlapem přes přední část chodidla pod tělo.",
                "dose": "2 × 20 m", "perWeek": 2,
                "steps": ["Dělejte drobné rychlé kroky s pomalým posunem vpřed.",
                          "Kolena se zvedají jen nízko a chodidlo došlapuje aktivně pod tělo přes přední část.",
                          "Kotník je pružný, trup vzpřímený a paže pracují rychle."],
                "mistakes": ["Došlap na patu nebo celé chodidlo.", "Příliš dlouhé kroky."]},
    "a_skip": {"name": "A-skip (liftink s poskokem)", "area": "běžecká technika",
               "how": "Poskočný krok s vysoko zvednutým kolenem švihové nohy a lehkým odrazem stojné nohy.",
               "dose": "2 × 20 m", "perWeek": 2,
               "steps": ["Jděte rytmem poskoku: pravá, pravá, levá, levá.",
                         "Při každém kroku zvedněte koleno švihové nohy do vodorovné polohy.",
                         "Stojná noha se lehce odráží z přední části chodidla a trup je vzpřímený.",
                         "Paže pracují jako při běhu, opačná ruka jde ke zvednutému koleni."],
               "mistakes": ["Záklon trupu.", "Došlap na patu."]},
    "heel_flicks": {"name": "Zakopávání", "area": "běžecká technika",
                    "how": "Klus s přitahováním pat k hýždím, kolena míří dolů a kroky jsou krátké.",
                    "dose": "2 × 20 m", "perWeek": 2,
                    "steps": ["Během lehkého klusu přitahujte paty k hýždím.",
                              "Kolena míří dolů, stehna se dopředu skoro nezvedají.",
                              "Kroky jsou krátké a rychlé s došlapem na přední část chodidla."],
                    "mistakes": ["Předklon trupu.", "Stehna jdou dopředu jako u liftinku."]},
    "b_skip": {"name": "B-skip (liftink s vykopnutím)", "area": "běžecká technika",
               "how": "Jako A-skip, jen se z horní polohy bérec vykopne dopředu a noha se aktivně stáhne pod tělo.",
               "dose": "2 × 20 m", "perWeek": 2,
               "steps": ["Začněte jako A-skip s vysoko zvednutým kolenem.",
                         "Z horní polohy vykopněte bérec dopředu, až je noha skoro propnutá.",
                         "Nohu pak aktivně stáhněte dolů a dozadu pod tělo, jako byste hrabali zem.",
                         "Došlap je na přední část chodidla pod těžištěm."],
               "mistakes": ["Došlap daleko před tělem.", "Záklon trupu."],
               "caution": "Při potížích se zadní stranou stehna ho zatím vynechte."},
    "straight_leg": {"name": "Předkopávání (běh s propnutými koleny)", "area": "běžecká technika",
                     "how": "Běh s propnutými koleny, nohy jdou střídavě dopředu jako nůžky a stahují zem pod tělo.",
                     "dose": "2 × 20 m", "perWeek": 2,
                     "steps": ["Běžte s propnutými koleny, nohy se střídají dopředu jako nůžky.",
                               "Chodidlo dopadá pod tělo na přední část a aktivně stahuje zem dozadu.",
                               "Trup je vzpřímený a paže pracují."],
                     "mistakes": ["Záklon trupu.", "Došlap daleko před těžištěm."],
                     "caution": "Při potížích se zadní stranou stehna ho zatím vynechte."},
    "bounding": {"name": "Odpichy", "area": "běžecká technika",
                 "how": "Dlouhé skoky střídavě z nohy na nohu s mohutnou prací paží.",
                 "dose": "2 × 20 m", "perWeek": 2,
                 "steps": ["Po krátkém rozběhu se odrážejte střídavě z jedné nohy na druhou do dlouhých skoků.",
                           "Koleno švihové nohy jde dopředu a nahoru, stojná noha se v odrazu propne.",
                           "Ve fázi letu držte tělo vzpřímeně a paže pracují mohutně.",
                           "Doskočte na přední část chodidla a hned se odrazte znovu."],
                 "mistakes": ["Doskok na patu.", "Příliš mnoho opakování hned na začátku."],
                 "caution": "Vynechte je při potížích s lýtkem nebo Achillovou šlachou, zatěžují je víc než běh."},
    "strides": {"name": "Stupňované rovinky", "area": "běžecká technika",
                "how": "Úsek 80 až 100 m s plynulým zrychlením do svižného, ale uvolněného tempa.",
                "dose": "4–6 × 80 m", "perWeek": 2,
                "steps": ["Po rozklusání si vyberte rovný úsek dlouhý 80 až 100 metrů.",
                          "Začněte volně a postupně zrychlujte zhruba na tempo závodu na 5 km.",
                          "Posledních 20 metrů povolte, běh má být uvolněný, ne sprint.",
                          "Zpět se vraťte chůzí nebo klusem a opakujte."],
                "mistakes": ["Plný sprint.", "Křeč v ramenou a obličeji."]},
}

# key → program. `match` = lower-case fragments of the body-map regions the program fits,
# `group` = "pain" (self-management of a complaint) or "performance" (core, running drills),
# `physio` = the Physiopedia page on the topic, linked for further reading only.
PHYSIO = "https://www.physio-pedia.com/"
PROGRAMS = [
    {"key": "achilles", "group": "pain", "physio": PHYSIO + "Achilles_Tendinopathy", "name": "Achillova šlacha", "weeks": 12,
     "match": ["achill"],
     "summary": "Postupně rostoucí zátěž šlachy výpony. Běhat se může dál, když bolest drží pravidlo níže.",
     "exercises": ["heel_raise_2", "heel_raise_1", "ecc_straight", "ecc_bent", "hops"],
     "evidence": "Zatěžování šlachy s průběžným sledováním bolesti vedlo ke zlepšení a pokračování v běhu mu neuškodilo "
                 "(Silbernagel et al., 2007). Spouštění paty ze schodu 3 × 15 dvakrát denně po 12 týdnů (Alfredson et al., 1998).",
     "refs": ["Silbernagel et al., 2007", "Alfredson et al., 1998"], "assumption": "Pořadí a poskoky až v závěru jsou pracovní předpoklad."},
    {"key": "calf", "group": "pain", "physio": PHYSIO + "Calf_Strain", "name": "Lýtko", "weeks": 6,
     "match": ["lýtk", "lytk", "gastrocnem", "soleus", "bérec"],
     "summary": "Síla lýtka propnutým i pokrčeným kolenem, na závěr pružnost poskoky.",
     "exercises": ["heel_raise_2", "heel_raise_1", "seated_calf", "hops"],
     "evidence": "Výpony vsedě, na dvou a na jedné noze a poskoky zatěžují lýtko a šlachu postupně víc, od půl násobku po sedminásobek tělesné hmotnosti "
                 "(Baxter et al., 2021).",
     "refs": ["Baxter et al., 2021"], "assumption": "Dávkování je pracovní předpoklad produktového týmu."},
    {"key": "plantar", "group": "pain", "physio": PHYSIO + "Plantar_Fasciitis", "name": "Plantární fascie (pata)", "weeks": 12,
     "match": ["plantár", "plantar", "pata"],
     "summary": "Výpon s ručníkem pod prsty s velkou zátěží, pomalu, obden.",
     "exercises": ["towel_raise"],
     "evidence": "Výpon na jedné noze s ručníkem pod prsty obden po 3 měsíce: 3 × 12 opakování s maximální zátěží, po 2 týdnech 4 × 10, "
                 "od 5. týdne 5 × 8 (Rathleff et al., 2015). Po 3 měsících byl výsledek lepší než po samotném protahování.",
     "refs": ["Rathleff et al., 2015"], "assumption": None},
    {"key": "knee", "group": "pain", "physio": PHYSIO + "Patellofemoral_Pain_Syndrome", "name": "Koleno vpředu", "weeks": 6,
     "match": ["kolen", "patel", "kvadricepsová šlacha"],
     "summary": "Posílení kyčle a kolena dohromady.",
     "exercises": ["side_abd", "clamshell", "bridge", "wall_squat", "step_up", "knee_ext"],
     "evidence": "U bolesti kolena vpředu odborný konsenzus doporučuje cvičení, nejlépe kombinaci cviků na kyčel a na koleno "
                 "(Collins et al., 2018). Kombinace ulevila od bolesti víc než samotné cviky na koleno (van der Heijden et al., 2016).",
     "refs": ["Collins et al., 2018", "van der Heijden et al., 2016"],
     "assumption": "Dávkování je pracovní předpoklad. Při bolesti přímo na šlaše pod čéškou se postup liší, poraďte se s fyzioterapeutem."},
    {"key": "itb", "group": "pain", "physio": PHYSIO + "Iliotibial_Band_Syndrome", "name": "IT pás a vnější strana kolena", "weeks": 6,
     "match": ["iliotib", "it band", "it pás", "hýžd", "glute"],
     "summary": "Síla a vytrvalost abduktorů kyčle, kontrola pánve na jedné noze.",
     "exercises": ["side_abd", "pelvic_drop", "clamshell", "sl_squat"],
     "evidence": "Běžci s bolestí IT pásu měli slabší abduktory kyčle a po 6 týdnech jejich posilování se 22 z 24 vrátilo k běhu bez bolesti "
                 "(Fredericson et al., 2000). Posilování abduktorů je nejčastější složkou úspěšné léčby (Sanchez-Alvarado et al., 2024).",
     "refs": ["Fredericson et al., 2000", "Sanchez-Alvarado et al., 2024"], "assumption": "Dávkování je pracovní předpoklad."},
    {"key": "shin", "group": "pain", "physio": PHYSIO + "Medial_Tibial_Stress_Syndrome", "name": "Holeň", "weeks": 6,
     "match": ["holen", "holeň", "tibial"],
     "summary": "Úprava zátěže a postupné posílení lýtka a holeně.",
     "exercises": ["heel_raise_2", "heel_raise_1", "toe_raise", "balance"],
     "evidence": "Žádná léčba bolesti holeně zatím není spolehlivě prokázaná (Winters et al., 2013). Nejlogičtější je úprava zátěže, postupné zatěžování "
                 "a posílení lýtka (Winters, 2017).",
     "refs": ["Winters et al., 2013", "Winters, 2017"],
     "assumption": "Slabší důkazy, dávkování je pracovní předpoklad. Bolest přímo na kosti nechte posoudit."},
    {"key": "hamstring", "group": "pain", "physio": PHYSIO + "Hamstring_Strain", "name": "Zadní strana stehna", "weeks": 8,
     "match": ["hamstring", "zákolen", "sedací hrbol"],
     "summary": "Šetrný začátek výdrží v mostu, pak síla v prodloužení.",
     "exercises": ["bridge_iso", "bridge", "sl_rdl", "nordic"],
     "evidence": "Programy s nordickým hamstringem snížily výskyt zranění zadní strany stehna zhruba na polovinu (van Dyk et al., 2019), "
                 "přesnější rozbor ale účinek za jistý nepovažuje (Impellizzeri et al., 2021). Mrtvý tah na jedné noze zlepšil sílu stejně jako nordický "
                 "hamstring (Behan et al., 2024).",
     "refs": ["van Dyk et al., 2019", "Impellizzeri et al., 2021", "Behan et al., 2024"],
     "assumption": "Nordický hamstring až bez bolesti. Dávkování je pracovní předpoklad."},
    {"key": "core", "group": "performance", "physio": PHYSIO + "Core_Stability", "name": "Core pro běžce", "weeks": 8,
     "match": [],
     "summary": "Vytrvalost svalů trupu a stabilita pánve, třikrát týdně po tréninku.",
     "exercises": ["plank", "side_plank", "dead_bug", "bird_dog", "bridge"],
     "evidence": "Osm týdnů cvičení středu těla třikrát týdně zlepšilo u vysokoškolských sportovců vytrvalost v planku, rovnováhu a ekonomiku běhu "
                 "(Hung et al., 2019). U rekreačních běžců zlepšilo přidání cviků na střed těla spojených s tréninkem nádechových svalů k intervalovému "
                 "tréninku ekonomiku a výkon v hodinovém běhu (Tong et al., 2016). Souhrn studií ale ukazuje velký účinek hlavně na vytrvalost trupu "
                 "a rovnováhu, na samotný sportovní výkon jen malý (Dong et al., 2023).",
     "refs": ["Hung et al., 2019", "Tong et al., 2016", "Dong et al., 2023"],
     "assumption": "Výběr cviků a dávkování je pracovní předpoklad, citované studie používaly jiné sestavy."},
    {"key": "drills", "group": "performance", "physio": PHYSIO + "Running_Biomechanics", "name": "Běžecká abeceda", "weeks": 8,
     "match": [],
     "summary": "Technická rozcvička před rychlejším tréninkem: skipinky, zakopávání, odpichy a rovinky.",
     "exercises": ["skipink", "a_skip", "heel_flicks", "b_skip", "straight_leg", "bounding", "strides"],
     "evidence": "Cviky abecedy napodobují části běžeckého kroku, s během ale nejsou totožné. A-skip, B-skip a zakopávání vedly k menšímu ohnutí "
                 "kotníku než běh a odpichy naopak k většímu výkonu v kotníku (Abran et al., 2024). A-skip zatěžoval lýtko méně než běh, "
                 "odpichy výrazně víc (Trowell et al., 2021). Že by abeceda sama zlepšila ekonomiku vytrvalostního běhu, zatím doloženo není.",
     "refs": ["Abran et al., 2024", "Trowell et al., 2021"],
     "assumption": "Výběr cviků, pořadí a dávkování vychází z trenérské praxe, ne z výzkumu. Zařaďte ji po rozklusání, ne na úplný začátek."},
]
PROGRAM_BY_KEY = {p["key"]: p for p in PROGRAMS}

REFERENCES = {
    "Alfredson et al., 1998": "Alfredson, H., Pietilä, T., Jonsson, P., & Lorentzon, R. (1998). Heavy-load eccentric calf muscle training for the treatment of chronic Achilles tendinosis. The American Journal of Sports Medicine, 26(3), 360–366.",
    "Silbernagel et al., 2007": "Silbernagel, K. G., Thomeé, R., Eriksson, B. I., & Karlsson, J. (2007). Continued sports activity, using a pain-monitoring model, during rehabilitation in patients with Achilles tendinopathy. The American Journal of Sports Medicine, 35(6), 897–906.",
    "Baxter et al., 2021": "Baxter, J. R., Corrigan, P., Hullfish, T. J., O'Rourke, P., & Silbernagel, K. G. (2021). Exercise progression to incrementally load the Achilles tendon. Medicine & Science in Sports & Exercise, 53(1), 124–130.",
    "Rathleff et al., 2015": "Rathleff, M. S., Mølgaard, C. M., Fredberg, U., Kaalund, S., Andersen, K. B., Jensen, T. T., Aaskov, S., & Olesen, J. L. (2015). High-load strength training improves outcome in patients with plantar fasciitis. Scandinavian Journal of Medicine & Science in Sports, 25(3), e292–e300.",
    "Collins et al., 2018": "Collins, N. J., Barton, C. J., van Middelkoop, M., et al. (2018). 2018 Consensus statement on exercise therapy and physical interventions to treat patellofemoral pain. British Journal of Sports Medicine, 52(18), 1170–1178.",
    "van der Heijden et al., 2016": "van der Heijden, R. A., Lankhorst, N. E., van Linschoten, R., Bierma-Zeinstra, S. M., & van Middelkoop, M. (2016). Exercise for treating patellofemoral pain syndrome: An abridged version of Cochrane systematic review. European Journal of Physical and Rehabilitation Medicine, 52(1), 110–133.",
    "Fredericson et al., 2000": "Fredericson, M., Cookingham, C. L., Chaudhari, A. M., Dowdell, B. C., Oestreicher, N., & Sahrmann, S. A. (2000). Hip abductor weakness in distance runners with iliotibial band syndrome. Clinical Journal of Sport Medicine, 10(3), 169–175.",
    "Sanchez-Alvarado et al., 2024": "Sanchez-Alvarado, A., Bokil, C., Cassel, M., & Engel, T. (2024). Effects of conservative treatment strategies for iliotibial band syndrome on pain and function in runners: A systematic review. Frontiers in Sports and Active Living, 6.",
    "Winters et al., 2013": "Winters, M., Eskes, M., Weir, A., Moen, M. H., Backx, F. J., & Bakker, E. W. (2013). Treatment of medial tibial stress syndrome: A systematic review. Sports Medicine, 43(12), 1315–1333.",
    "Winters, 2017": "Winters, M. (2017). Medial tibial stress syndrome: Diagnosis, treatment and outcome assessment (PhD Academy Award). British Journal of Sports Medicine.",
    "van Dyk et al., 2019": "van Dyk, N., Behan, F. P., & Whiteley, R. (2019). Including the Nordic hamstring exercise in injury prevention programmes halves the rate of hamstring injuries. British Journal of Sports Medicine, 53(21), 1362–1370.",
    "Impellizzeri et al., 2021": "Impellizzeri, F. M., McCall, A., & van Smeden, M. (2021). Why methods matter in a meta-analysis: A reappraisal showed inconclusive injury preventive effect of Nordic hamstring exercise. Journal of Clinical Epidemiology.",
    "Behan et al., 2024": "Behan, F. P., et al. (2024). Implementing hamstring injury prevention programmes remotely: A randomised proof of concept trial. BMJ Open Sport & Exercise Medicine.",
    "Warden et al., 2014": "Warden, S. J., Davis, I. S., & Fredericson, M. (2014). Management and prevention of bone stress injuries in long-distance runners. Journal of Orthopaedic & Sports Physical Therapy, 44(10), 749–765.",
    "Hung et al., 2019": "Hung, K.-C., Chung, H.-W., Yu, C. C.-W., Lai, H.-C., & Sun, F.-H. (2019). Effects of 8-week core training on core endurance and running economy. PLoS ONE, 14(3), e0213158.",
    "Tong et al., 2016": "Tong, T. K., McConnell, A. K., Lin, H., Nie, J., Zhang, H., & Wang, J. (2016). \"Functional\" inspiratory and core muscle training enhances running performance and economy. Journal of Strength and Conditioning Research, 30(10), 2942–2951.",
    "Dong et al., 2023": "Dong, K., Yu, T., & Chun, B. (2023). Effects of core training on sport-specific performance of athletes: A meta-analysis of randomized controlled trials. Behavioral Sciences, 13(2), 148.",
    "Abran et al., 2024": "Abran, G., et al. (2024). A comparison of foot and ankle biomechanics during running drills and distance running. Sports Biomechanics.",
    "Trowell et al., 2021": "Trowell, D., et al. (2021). A comparison of plantarflexor musculotendon unit output between plyometric exercises and running. Journal of Science and Medicine in Sport.",
}


def programs_for_regions(regions: list[str]) -> list[str]:
    """Program keys that fit the marked pain regions, most marked first."""
    hits: dict[str, int] = {}
    for reg in regions:
        r = (reg or "").lower()
        for p in PROGRAMS:
            if any(m in r for m in p["match"]):
                hits[p["key"]] = hits.get(p["key"], 0) + 1
    return sorted(hits, key=lambda k: -hits[k])


def _exercise_links() -> dict:
    """Exercise id → the Physiopedia pages of the programs it belongs to (further reading)."""
    out: dict[str, list] = {}
    for p in PROGRAMS:
        for x in p["exercises"]:
            if not any(lk["url"] == p["physio"] for lk in out.setdefault(x, [])):
                out[x].append({"url": p["physio"], "topic": p["name"]})
    return out


def library() -> dict:
    links = _exercise_links()
    ex = {k: {**v, "links": links.get(k, [])} for k, v in EXERCISES.items()}
    return {"exercises": ex, "programs": PROGRAMS, "painRule": PAIN_RULE, "references": REFERENCES, "reviewed": False,
            "source": "Texty cviků a ilustrace jsou vlastní. Physiopedia slouží jen jako odkaz na další čtení."}
